Feat - Daily Deck
gator-labs/chomp pull request #159
Opened 2024-05-29 13:17 UTC by danijel-radomiljac

Implemented new daily deck design.

https://app.clickup.com/t/86byy1qnu

2024-05-30 12:41 UTC, marvinmarnold requested changes

2024-05-30 12:41 UTC, marvinmarnold commented on app/components/DailyDeckTitle/DailyDeckTitle.tsx
> +          <p className="text-sm">
Why is this lorem ipsum?

2024-05-30 19:06 UTC, danijel-radomiljac commented on app/components/DailyDeckTitle/DailyDeckTitle.tsx
> +          <p className="text-sm">
Because I don't have actual text for this

2024-05-31 13:19 UTC, marvinmarnold approved these changes
approving now  but will check closer later

2024-05-31 13:37 UTC, merged