feat: minor ui fixes and updates
gator-labs/chomp pull request #256
Opened 2024-06-08 16:14 UTC by adithyaakrishna

**Description:**
- Fixes the width of carousel cards
- Fixes loader to animate clockwise
- Update `.env.example` to mention required variables
- Added commitlint to streamline commit messages (Follows conventional commit messages spec)
- Move redundant functions to utils

2024-06-10 13:52 UTC, AnteVuletic commented on tsconfig.json
> +      "@chomp/*": ["./*"]
I would prefer if we did not merge this

2024-06-10 14:23 UTC, marvinmarnold requested changes
@adithyaakrishna thanks for this. But this is a big commit with some opinionated changes we would need to check internally. Could you just include the .env.example changes for now?

2024-06-11 06:08 UTC, adithyaakrishna commented on app/actions/deck/factories.ts
> +          durationMilliseconds: ONE_MINUTE_IN_MILISECONDS,
Oops! My bad, I missed this one. Thanks for pointing it out. Will update it :)

2024-06-11 06:09 UTC, adithyaakrishna commented
@marvinmarnold Gotcha, should I keep the typo ones or revert them as well?

2024-06-18 13:10 UTC, closed without merging