Feat/deck scripts
gator-labs/chomp pull request #285
Opened 2024-06-18 06:05 UTC by boranfurkan

- Description:
- ClickUp links: https://app.clickup.com/t/86bz6c4nm, https://app.clickup.com/t/86bz7cxrp
- What are the acceptance criteria? What are the steps to test that this code is working?

In this pr I have created deck scripts for creating both objective and subjective questions. Script creates number of users and make them answer the question randomly for subjective script. On the other hand, you can give extra paramater in the terminal to make  newly created users choose your answer.

2024-06-18 21:42 UTC, marvinmarnold requested changes

2024-06-18 21:42 UTC, marvinmarnold commented on scripts/CreateObjectiveWithAnswers.ts
> +          percentage: Math.floor(Math.random() * 100),
The sum of percentages for a user's answer to a single question should add up to 100%. 

If yes is 75%, then the corresponding no response for the user should be 25%. This code gives a random value to both of the users answers.

2024-06-18 22:51 UTC, boranfurkan commented on scripts/CreateObjectiveWithAnswers.ts
> +          percentage: Math.floor(Math.random() * 100),
Oh fixing it asap. Thanks for letting me know

2024-06-19 13:41 UTC, marvinmarnold commented on package.json
> +    "dev:subj-question": "ts-node scripts/CreateSubjectiveWithAnswers.ts first",
Can you remove 'first' from these commands so that we can run `yarn dev:subj-question second`. I realize I was the one who introduced this pattern, thanks for updating.

2024-06-19 13:48 UTC, marvinmarnold commented on scripts/CreateObjectiveWithAnswers.ts
>                revealTokenAmount: 100,
Github won't let me comment on the line I want to. But lines 50+51 are wrong. isCorrect should be based on optionToSelect, not hardcoded.

2024-06-24 17:22 UTC, merged