Feat/refactoring dynamic
gator-labs/chomp pull request #322
Opened 2024-07-05 20:19 UTC by yash431garg

- Description:
- ClickUp links:
- What are the acceptance criteria? What are the steps to test that this code is working?

Dynamic bonk burn flow for mini app and validate data api. 
Unify User Clickup: https://app.clickup.com/t/86bz8r9j8
Dynamic Burn Flow: https://app.clickup.com/t/86bz6yteb

Unify User: Getting user details by passing the hash from mini app. 
Burn Flow: Bonk burn successfully. 
Checkout  @Dchomp_bot to verify the burn flow

2024-07-06 00:41 UTC, marvinmarnold requested changes
We will keep this PR open until Chomp Bot is complete. You should branch off of this for future PRs @yash431garg @neel-ds.

That said, please review the comments below.

2024-07-06 00:41 UTC, marvinmarnold commented on app/api/validate/route.ts
> +  // if () {
Cleanup debug code

2024-07-06 00:41 UTC, marvinmarnold commented on app/bot/page.tsx
> +      if (balance < 1000) {
Does this take decimals into consideration?

2024-07-06 00:41 UTC, marvinmarnold commented on app/login/page.tsx
> +export default function Page() {
Why does this page need to be changed? Is this a rebase mistake or intentional?

2024-07-06 00:41 UTC, marvinmarnold commented on app/tutorial/page.tsx
> +"use client";
Why does this page need to be changed? Is this a rebase mistake or intentional?

2024-07-06 00:41 UTC, marvinmarnold commented on echo
> +  feat/home-page
Remove from PR

2024-07-06 09:32 UTC, yash431garg commented on app/api/validate/route.ts
> +  // if () {
Sure, I will clean it.

2024-07-06 09:32 UTC, yash431garg commented on app/bot/page.tsx
> +      if (balance < 1000) {
It is checking it in lamports.

2024-07-06 09:33 UTC, yash431garg commented on app/login/page.tsx
> +export default function Page() {
It is rebase I think it was an upcoming change.

2024-07-06 09:33 UTC, yash431garg commented on app/tutorial/page.tsx
> +"use client";
It is also rebase.

2024-07-09 01:24 UTC, marvinmarnold commented on app/api/validate/route.ts
> +  // if () {
@yash431garg this isn't the result of a rebase. this is showing up because you haven't rebased in a while. Let's keep this PR up-to-date with main. Basically, just rebase this branch onto main now. Then we'll do again before merging.

![Screenshot 2024-07-08 at 8 23 22 PM](https://github.com/gator-labs/chomp/assets/1311030/1b5973f0-3677-4dd5-8211-a3559901cc59)

2024-07-09 19:48 UTC, marvinmarnold commented on .env.example
> +NEXT_PUBLIC_TURNKEY_API_BASE_URL=https://api.turnkey.com
Remove unused env vars like Turnkey that are leftovers from my code.

2024-07-09 19:51 UTC, marvinmarnold commented on package.json
> +    "@dynamic-labs/sdk-react-core": "3.0.0-alpha.5",
Note that this needs to be stable before we merge.

2024-07-09 19:59 UTC, yash431garg commented on .env.example
> +NEXT_PUBLIC_TURNKEY_API_BASE_URL=https://api.turnkey.com
Okay, we kept it thinking you were asking to implement it in the future.

2024-08-02 19:14 UTC, marvinmarnold commented
@yash431garg @neel-ds can you fix the conflicts in this PR? I'm mostly worried about package.json. Don't want some version incompatibility to sneak up on us.

2024-08-21 23:12 UTC, marvinmarnold requested changes
I'll review again after we merge https://github.com/gator-labs/chomp/pull/427

2024-08-21 23:12 UTC, marvinmarnold commented on .github/workflows/migrations.yml
> +  migrate_demo:
This should be removed before merge

2024-08-21 23:12 UTC, marvinmarnold commented on app/actions/chompResult.ts
> +export async function getDeckThatNeedChompResultBasedOnRevealedQuestionIds(
Does this or any other queries need to be updated based on: https://github.com/gator-labs/chomp/pull/420

2024-08-23 18:47 UTC, neel-ds commented on app/actions/chompResult.ts
> +export async function getDeckThatNeedChompResultBasedOnRevealedQuestionIds(
Thank you! We have updated the required changes.

2024-08-23 18:48 UTC, neel-ds commented on .github/workflows/migrations.yml
> +  migrate_demo:
Sure! We will remove this before the merge.

2024-08-27 19:53 UTC, marvinmarnold requested changes
Unfortunately there are still a few security issues. Some of the anti-patterns predate this PR and I'm only noticing now. See: https://linear.app/gator/issue/PROD-212/lockdown-server-actions

2024-08-27 19:53 UTC, marvinmarnold commented on app/actions/fungible-asset.ts
> +  if (!userId) userId = payload?.sub ?? "";
This line doesn't make sense to me. The if statement is redundant with `??`.

2024-08-27 19:53 UTC, marvinmarnold commented on app/actions/fungible-asset.ts
> -  const userId = payload?.sub ?? "";
@danijel-radomiljac is the existing code secure? Why don't we stop execution if there is no userId?

2024-08-27 19:53 UTC, marvinmarnold commented on app/application/answer/frame/page.tsx
> +    const vals = searchParams?.get("vals");
This file can be deleted, it is unused.

2024-08-27 19:53 UTC, marvinmarnold commented on app/queries/home.ts
> +export async function queryQuestionsForReadyToReveal(
Exporting here is also making this function public.

2024-08-27 19:53 UTC, marvinmarnold commented on app/queries/processBurnClaim.ts
> +export async function revealAllSelected(
This looks like a blocker. Needs auth or should be moved outside of the  `app` directory.

2024-08-27 19:53 UTC, marvinmarnold commented on app/queries/user.ts
> +export async function getUserByTelegram(telegramId: string) {
All of these functions look unprotected.

2024-08-28 15:13 UTC, yash431garg commented on app/queries/user.ts
> +export async function getUserByTelegram(telegramId: string) {
Agree, we need to add some kind of auth mechanism here.

2024-08-28 15:15 UTC, yash431garg commented on app/queries/processBurnClaim.ts
> +export async function revealAllSelected(
We can add auth here but didn't completely understand the reason behined moving it outside of app directory.

2024-08-28 15:18 UTC, yash431garg commented on app/queries/home.ts
> +export async function queryQuestionsForReadyToReveal(
Understood, basically we need to have auth in the function if we want to export them.

2024-10-17 01:47 UTC, marvinmarnold commented
@yash431garg @neel-ds, new work will follow this: https://linear.app/gator/issue/PROD-400/telegram-mini-app-dynamic-sign-in-notifications-spike

2024-10-17 01:47 UTC, closed without merging