feat: reveal questions miniapp
gator-labs/chomp pull request #374
Opened 2024-07-31 10:24 UTC by neel-ds

- Description:
Add reveal questions flow
- ClickUp links:
https://app.clickup.com/t/86bzjfvgh
- What are the acceptance criteria? What are the steps to test that this code is working?

2024-08-01 17:07 UTC, marvinmarnold commented on app/components/Bot/Bot.tsx
> +      if (balance < 1000) {
This should be the actual amount to burn and not hardcoded to 1000.

2024-08-01 17:18 UTC, marvinmarnold requested changes

2024-08-01 17:18 UTC, marvinmarnold commented on app/components/Bot/Bot.tsx
> +      const tx = await genBonkBurnTx(primaryWallet!.address, blockhash, 10);
This should not be hardcoded to 10.

2024-08-01 17:18 UTC, marvinmarnold commented on app/components/Bot/Bot.tsx
> +      const response = await fetch(`/api/validate`, options);
There is no point in verifying tg ID on the client side. We can't trust that clients will respect this code.

It also leaves the server functions unprotected. I will clarify the fix in more comments below.

2024-08-01 17:18 UTC, marvinmarnold commented on app/components/Bot/Bot.tsx
> +        <svg
Normally we define SVGs in their own file. See app/components/Icons

2024-08-01 17:18 UTC, marvinmarnold commented on app/queries/bot.ts
> +export const getUserId = async (telegramId: string) => {
This is the continuation of my explanation about how we should be validating. 

Currently we are validating from the client then sending requests to the endpoints defined in this file. But these endpoints are unprotected. This means anybody can invoke this endpoint and get information about any user.

Instead, the telegram payload should be supplied here. The payload should be verified server side in this code, not on the client.

2024-08-01 17:37 UTC, neel-ds commented on app/components/Bot/Bot.tsx
> +      if (balance < 1000) {
This issue will be resolved in Yash's PR. It's not meant to be used here. 
cc: @yash431garg

2024-08-01 17:37 UTC, neel-ds commented on app/components/Bot/Bot.tsx
> +      const tx = await genBonkBurnTx(primaryWallet!.address, blockhash, 10);
Likewise, onBurn function will be used in Yash's PR. Please consider it cc: @yash431garg

2024-08-01 17:39 UTC, neel-ds commented on app/components/Bot/Bot.tsx
> +        <svg
This spinner has been replaced by the Chomp Loader as mentioned cc: @yash431garg

2024-08-01 23:33 UTC, Yihwan commented
PROD-30

2024-08-02 10:11 UTC, yash431garg commented on app/components/Bot/Bot.tsx
> +      if (balance < 1000) {
Sure, It will removed from here and we will show insufficient balance in the pop up instead. I will update this in my PR.

2024-08-02 10:12 UTC, yash431garg commented on app/components/Bot/Bot.tsx
> +      const tx = await genBonkBurnTx(primaryWallet!.address, blockhash, 10);
Okay, similarly for this as well will update it in the upcoming pr.

2024-08-02 16:28 UTC, marvinmarnold approved these changes
I think there are still some security issues. I'll create a follow up issue for that so we can merge this and I can start testing.

2024-08-02 16:28 UTC, marvinmarnold commented on app/queries/bot.ts
> +export const getUserData = async (telegramId: string) => {
I still don't think these methods are properly protected. Malicious browser code can invoke this method by supplying someone else's telegram ID.

Instead, this method should accept the entire signed payload from Telegram. That should be verified here, on the server. Then only then doe we invoke the underlying API endpoint.

2024-08-02 16:53 UTC, merged