fix: correct regular decks logic
gator-labs/chomp pull request #380
Opened 2024-08-01 15:26 UTC by neel-ds

- Description:
Correct the logic of fetching Regular Decks in Questions API

- ClickUp links:
https://app.clickup.com/t/86bzqmywj

- What are the acceptance criteria? What are the steps to test that this code is working?
Test route /api/question/get?userId={userId}

2024-08-01 17:22 UTC, marvinmarnold requested changes

2024-08-02 16:32 UTC, marvinmarnold approved these changes
@neel-ds you can merge now but I'll still try to get clarity from @danijel-radomiljac

2024-08-02 16:32 UTC, marvinmarnold commented on app/api/question/get/route.ts
> +    const deckQuestions = await prisma.deckQuestion.findMany({
@danijel-radomiljac will this change have any unintended consequences on the rest of the app?

2024-08-02 16:56 UTC, merged

2024-08-05 08:09 UTC, danijel-radomiljac commented on app/api/question/get/route.ts
> +    const deckQuestions = await prisma.deckQuestion.findMany({
No it should be ok.