PROD-83: Fix/optimize burn fee
gator-labs/chomp pull request #419
Opened 2024-08-16 09:37 UTC by yash431garg

✅ Add Linear ID (e.g., `PROD-123`) to PR title to automatically link issue

- Description
Added Estimate priority function from helius api to get an approrate fees along with adding compute unit in the transaction to increase the sucess rate of the burn transation with very low fees
- What are the steps to test that this code is working?
Low priority fees, high success rate. 
- Screen shots or recordings for UI changes
There is no ui changes

2024-08-19 13:46 UTC, marvinmarnold commented on app/utils/solana.ts
> +  tx.add(modifyComputeUnits);
I read somewhere that it's better to add the fee txs before the actual burn tx. Should we do that here?

2024-08-19 13:46 UTC, marvinmarnold commented on app/utils/solana.ts
> +  const modifyComputeUnits = ComputeBudgetProgram.setComputeUnitLimit({
This is twice as high as needed (4810). I think that's actually fine for now, if your compute price is right. But any reason we shouldn't use some lower hardcoded values like 5500?

2024-08-20 07:44 UTC, yash431garg commented on app/utils/solana.ts
> +  tx.add(modifyComputeUnits);
Yea, I also find out that it is good to keep it above the actual burn. Will be updated in next burn.

2024-08-20 07:48 UTC, yash431garg commented on app/utils/solana.ts
> +  const modifyComputeUnits = ComputeBudgetProgram.setComputeUnitLimit({
Now, I have added it to a fix number of 5000 with 25% additonal to prevent compute unit budget fail error. 
![Screenshot 2024-08-20 at 1 18 02 PM](https://github.com/user-attachments/assets/12db7bcf-82db-4556-8e0c-5ccfaf99ac1a)

2024-08-20 16:13 UTC, marvinmarnold requested changes
@yash431garg this looks good. But I think we should merge this into `main`. Can you reopen the PR into `main` branch?

2024-08-20 16:39 UTC, marvinmarnold commented
Replaced with: https://github.com/gator-labs/chomp/pull/426

2024-08-20 16:39 UTC, closed without merging