Feat/lockdown chomp backend
gator-labs/chomp pull request #427
Opened 2024-08-20 16:59 UTC by yash431garg

✅ Add Linear ID (e.g., `PROD-123`) to PR title to automatically link issue

- Description
Updated queries to not trust untrusted data and use telegram and dynamic payload instead.
- What are the steps to test that this code is working?
It does not include code changes mostly include enchancements and fixes.
- Screen shots or recordings for UI changes

2024-08-21 22:59 UTC, marvinmarnold requested changes
My biggest confusion is why there are so many fetch requests. My impression is that this code was moved from chomp-bot repo, but now fetch requests no longer needed from miniapp to chomp API since they are hosted part of same app. Can be replaced with server actions?

2024-08-21 22:59 UTC, marvinmarnold commented on app/queries/bot.ts
> +      `${process.env.NEXT_PUBLIC_API_URL}/question/reveal?userId=${userData.id}`,
1. Can you drop a Github link to where this endpoint defined?
2. Why would this need to be a fetch request instead of invoking a server action/function?

2024-08-21 22:59 UTC, marvinmarnold commented on app/queries/bot.ts
> +  tgId: string,
id and telegramId are still being supplied by the client. A malicious user could modify these.

2024-08-21 22:59 UTC, marvinmarnold commented on app/queries/bot.ts
> +export const isUserExistByEmail = async (
Better name: doesUserExistByEmail

2024-08-21 22:59 UTC, marvinmarnold commented on app/queries/bot.ts
> +    method: "GET",
There should be an auth mechanism here too. We don't want to make it possible to know if an arbitrary email has registered.

2024-08-21 22:59 UTC, marvinmarnold commented on app/queries/bot.ts
> +export const getRevealQuestionsData = async (authToken: string) => {
Not clear what this method does from the name. Generally, more comments would be helpful at the top of API methods.

2024-08-22 08:23 UTC, yash431garg commented on app/queries/bot.ts
> +export const getRevealQuestionsData = async (authToken: string) => {
Sure, I will add the comment for this function and will keep in mind for future changes.

2024-08-22 08:26 UTC, yash431garg commented on app/queries/bot.ts
> +      `${process.env.NEXT_PUBLIC_API_URL}/question/reveal?userId=${userData.id}`,
1. Here is the github link of the above endpoint: [Get Reveal Quesiton](https://github.com/gator-labs/chomp/blob/feat/lockdown-chomp-backend/app/api/question/reveal/route.ts)
2. We use this api in bot as well to fetch the number of question which are ready to reveal that's why it is a fetch request instead of a server action.

2024-08-22 08:28 UTC, yash431garg commented on app/queries/bot.ts
> +export const isUserExistByEmail = async (
Sure, I have updated this.

2024-08-23 10:32 UTC, merged