PROD-168 updated routing and navigation for new home screen
gator-labs/chomp pull request #436
Opened 2024-08-25 13:49 UTC by AndrejRadomiljac

✅ Add Linear ID (e.g., `PROD-123`) to PR title to automatically link issue

- Description:
   The bullet list of updates is available in the following [link](https://linear.app/gator/issue/PROD-168/first-pass-on-new-home-screen). 
  General updates: New home screen consists of the previous dashboard page and previous application page. Updating routing for profile routes. Redirection setup for the old urls. Removed avatar click on the application page. Removed stats cards (some of them).
- What are the steps to test that this code is working?
- Screen shots or recordings for UI changes
**Current staging**
![Screenshot 2024-08-25 at 15 47 22](https://github.com/user-attachments/assets/f9884f39-3195-4e28-b2b0-89c01d703bed)

**Incoming changes**
![Screenshot 2024-08-25 at 15 47 48](https://github.com/user-attachments/assets/401102d4-d440-429b-973a-ba6386adfcc1)

2024-08-26 12:40 UTC, danijel-radomiljac requested changes

2024-08-26 12:40 UTC, danijel-radomiljac commented on next.config.js
> +      },
I think that this is not necessary. Because we configured routing via folder structure.

2024-08-26 15:55 UTC, Yihwan commented
thanks starting review now

2024-08-26 15:56 UTC, Yihwan commented on app/application/history/page.tsx
>  import { getTotalClaimableRewards } from "@/app/actions/history";
ordinarily we would want to set up redirects for dead urls (e.g., in cloudflare), but i am fine skipping this step this time because i confirmed we never linked to these pages directly. lmk if anyone feels differently.

2024-08-26 16:01 UTC, danijel-radomiljac commented on app/application/history/page.tsx
>  import { getTotalClaimableRewards } from "@/app/actions/history";
What do you mean by dead urls?

2024-08-26 16:01 UTC, Yihwan commented
can we have the scrollbar only how on scroll? on brave desktop mac scrollbar seems visible even in non scrolling state. 

i am also fine hiding the scroll bar entirely. normally this is not great for desktop accessibility but i think it is fine as long as we have "mobile only" designs like now 

<img width="648" alt="Screenshot 2024-08-26 at 08 59 18" src="https://github.com/user-attachments/assets/b9a2515e-2a37-414f-93df-2277b47a6ee1">

2024-08-26 16:03 UTC, Yihwan commented
clicking "reveal" from History > Reveal unchomped question> Burn 10 BONK seems to infinitely load, but maybe this is expected for preview deployment? 
<img width="537" alt="Screenshot 2024-08-26 at 09 02 57" src="https://github.com/user-attachments/assets/d3f0ccd1-e251-40a1-a629-5e890b496f0d">

2024-08-26 16:05 UTC, Yihwan commented
pls remove this row from both dashboard and leaderboard
<img width="537" alt="Screenshot 2024-08-26 at 09 05 00" src="https://github.com/user-attachments/assets/de2dd1e9-8ade-4562-b546-92a0ab72bd24">

2024-08-28 18:44 UTC, marvinmarnold approved these changes
Code: lgtm

2024-08-29 15:31 UTC, marvinmarnold commented
@AndrejRadomiljac looks like you are good to merge

2024-08-29 20:52 UTC, merged