PROD-170: Feat/treasury alert
gator-labs/chomp pull request #440
Opened 2024-08-28 07:35 UTC by yash431garg

✅ Add Linear ID (e.g., `PROD-123`) to PR title to automatically link issue

- Description
Low balance treasury alerts
- What are the steps to test that this code is working?
Getting notification on slack channels #_product, #eng-alerts regarding drop in wallet balance below 0.1 Sol and 10M Bonk
- Screen shots or recordings for UI changes
No ui changes for this tasks. But here is a notification screenshot on slack. 
![Screenshot 2024-08-28 at 1 05 10 PM](https://github.com/user-attachments/assets/bd86e528-3829-43de-9dc2-46e085d02090)

2024-08-28 17:45 UTC, marvinmarnold requested changes

2024-08-28 17:45 UTC, marvinmarnold commented on app/actions/claim.ts
> +      `Wallet balance dropped below threshold Refill here: ${treasuryAddress}, Current Balance: ${treasurySolBalance} SOL, ${treasuryBonkBalance} BONK.`,
Can you reorder text so that most important information is in Slack preview: `Treasury balance low: X SOL, Y BONK. Squads: SQUADS_URL. Solscan: SOLSCAN_URL`

See Linear for additional details: https://linear.app/gator/issue/PROD-170/low-balance-treasury-alerts#comment-13ce2b4b

2024-08-30 09:15 UTC, yash431garg commented on app/actions/claim.ts
> +      `Wallet balance dropped below threshold Refill here: ${treasuryAddress}, Current Balance: ${treasurySolBalance} SOL, ${treasuryBonkBalance} BONK.`,
Will be updated in the next commit.

2024-08-30 15:11 UTC, marvinmarnold commented
@yash431garg have you added the env vars to vercel for all environments?

2024-08-31 16:58 UTC, yash431garg commented
@marvinmarnold I have added env for squads in production. Should I keep the same squads url for dev and preview branches as well?

2024-09-02 15:59 UTC, marvinmarnold approved these changes

2024-09-02 22:56 UTC, merged