PROD-175/mixpanel-spike
gator-labs/chomp pull request #442
Opened 2024-08-28 11:11 UTC by danijel-radomiljac

We are showing userID in every event.

In login we are showing wallet connector.

In question reveal we are showing transactionSignature, burnedAmount and questionId.

In claimed question we are showing transactionSignature, claimedAmount and questionId.

![Screenshot 2024-08-28 at 13 10 26](https://github.com/user-attachments/assets/2bc41001-c69b-444d-9587-fbfd940e485f)

2024-08-28 18:11 UTC, Yihwan commented
also defer to @marvinmarnold for actual code review

2024-08-28 18:20 UTC, marvinmarnold requested changes

2024-08-28 18:20 UTC, marvinmarnold commented on package.json
> +    "mixpanel-browser": "^2.55.0",
Is this actually being used? If not, let's remove.

2024-08-29 08:57 UTC, danijel-radomiljac commented
> thanks! some questions:
> 
> * is it possible to get city/country data with server side analytics? or is that only available client side?
> * can you send the actual question content in addition to question IDs? primary users of this dashboard will likely be non technical/not be able to lookup questions by ID easily. we might add more question-related content later, but for now i think just ID and the actual question text is sufficient.

yes we can track city/country but we would need to use some external service and probably one of paid versions: https://ipapi.com/product

2024-08-29 15:34 UTC, marvinmarnold requested changes

2024-08-29 15:34 UTC, marvinmarnold commented on lib/mixpanel.ts
> +    distinct_id: userUUID,
@danijel-radomiljac it looks like if we include `ip`, Mixpanel will automatically geolocate

![Screenshot 2024-08-29 at 10 34 20 AM](https://github.com/user-attachments/assets/747858d5-1b33-4b56-a242-99ef7d205253)

2024-08-30 15:16 UTC, marvinmarnold requested changes

2024-08-30 15:16 UTC, marvinmarnold commented on app/api/mixpanel/route.ts
> +    mixpanel.track(event, properties);
@danijel-radomiljac after second look, I actually think it's better to pull IP directly from the request on the server: https://nextjs.org/docs/pages/api-reference/functions/next-request#ip

That way we don't have to do an extra API request client side.

2024-08-30 16:49 UTC, marvinmarnold approved these changes

2024-08-30 16:53 UTC, merged