PROD-197/create-campaigns-page
gator-labs/chomp pull request #443
Opened 2024-08-28 12:13 UTC by danijel-radomiljac

2024-08-28 18:42 UTC, marvinmarnold requested changes

2024-08-28 18:42 UTC, marvinmarnold commented on app/campaings/page.tsx
> +import { getCampaigns } from "@/app/queries/campaign";
`campaigns` misspelled in `app/campaings/page.tsx` leading to incorrect path

2024-08-28 18:42 UTC, marvinmarnold commented on app/campaings/page.tsx
> +  const campaigns = await getCampaigns();
Should only show campaigns that are active and visible

2024-08-29 08:24 UTC, danijel-radomiljac commented on app/campaings/page.tsx
> +  const campaigns = await getCampaigns();
Why active and visible? If thats the case then why do we have two booleans?

2024-08-29 14:33 UTC, marvinmarnold commented on app/campaings/page.tsx
> +  const campaigns = await getCampaigns();
tbh I'm not sure the exact reason, but it's one of the requirements in Linear. Probably because we are focused on Breakpoint and we don't want to confuse users with campaigns they can't participate in.

In the past, we've talked about wanting to keep showing campaign results (isVisible = true), even if the campaign is no longer ongoing (isActive = false).

@Yihwan

2024-08-30 15:48 UTC, Yihwan commented on app/campaings/page.tsx
> +  const campaigns = await getCampaigns();
we are working on designs to better distinguish between active/inactive campaigns but those aren't ready yet. so for now, i'd only include active/visible, and then possibly add in inactive later once the designs are ready/if we need to.

2024-09-02 15:59 UTC, marvinmarnold approved these changes

2024-09-02 16:28 UTC, merged