PROD-222 Add more sentry errors
gator-labs/chomp pull request #464
Opened 2024-09-04 09:32 UTC by neel-ds

- Description
Handle exceptions via Sentry in more actions and upgrade the current exception
- What are the steps to test that this code is working?
Try to break something in login, reveal, burn or claim
- Screen shots or recordings for UI changes
NA

2024-09-04 22:17 UTC, marvinmarnold requested changes

2024-09-04 22:17 UTC, marvinmarnold commented on app/actions/answer.ts
> +          amount: pointsPerAction[TransactionLogType.AnswerQuestion],
What do these changes have to do with the Linear issue?

2024-09-05 07:37 UTC, neel-ds commented on app/actions/answer.ts
> +          amount: pointsPerAction[TransactionLogType.AnswerQuestion],
I wrapped the code in a try-catch block, which caused some restructuring across different lines. Technically, there are no functional changes, but Git is detecting it as code changes. I compared it line by line. Please ignore it.

2024-09-06 19:34 UTC, marvinmarnold commented
@neel-ds you will follow up with additional commits, right?

2024-09-09 05:35 UTC, neel-ds commented
> @neel-ds you will follow up with additional commits, right?

Yes!

2024-09-09 06:02 UTC, neel-ds commented on app/hooks/useReveal.ts
> +          Sentry.captureException(burnError);
done.

2024-09-09 14:38 UTC, marvinmarnold approved these changes

2024-09-09 15:01 UTC, merged