Prod 146: Design freindly errors
gator-labs/chomp pull request #493
Opened 2024-09-13 06:57 UTC by yash431garg

- Description
Handle runtime errors with error pages.
- What are the steps to test that this code is working?
1. 404 page on wrong page route
2. 400 client error page on client exception
3. 500 server error page on server exception
- Screen shots or recordings for UI changes
![Screenshot 2024-09-13 at 12 25 48 PM](https://github.com/user-attachments/assets/ce93a4f4-35af-4441-b313-81e52a778c2f)

2024-09-13 07:21 UTC, yash431garg commented
@Yihwan Can you please review the desings here?

2024-09-16 08:08 UTC, Yihwan commented on app/components/Icons/RefreshIcon.tsx
> +import { ICON_DEFAULT_WIDTH_HEIGHT, IconProps } from ".";
we no longer need to import icons manually. pls try importing from https://lucide.dev/guide/packages/lucide-react and see if it is easy to get it to look the same as before; if not we can address in separate PR

2024-09-16 08:09 UTC, Yihwan commented on app/not-found.tsx
> +          (stack trace, other technical info that may be helpful for debugging)
pls remove all placecholder copy. it is helpful for checking design but if no actual copy was provided pls just remove

2024-09-16 08:09 UTC, Yihwan requested changes
icon changes are optional if they require more discussion, but we have to remove all placeholder copy before this can be merged

2024-09-16 10:39 UTC, yash431garg commented on app/not-found.tsx
> +          (stack trace, other technical info that may be helpful for debugging)
Sure, I will remove this.

2024-09-16 16:13 UTC, yash431garg commented on app/components/Icons/RefreshIcon.tsx
> +import { ICON_DEFAULT_WIDTH_HEIGHT, IconProps } from ".";
I have changed using lucide.

2024-09-17 03:35 UTC, marvinmarnold requested changes

2024-09-17 03:35 UTC, marvinmarnold commented on app/components/ErrorBoundary/ErrorBoundary.tsx
> +    Sentry.captureException(error);
Let's use a custom error type for this so it's easier to track. Like this: https://github.com/gator-labs/chomp/blob/1f14fbbf2335392fff2c3d18af35b3443caa58d3/app/providers/DynamicProvider.tsx#L64

You can call it ErrorBoundaryError or something

2024-09-17 08:05 UTC, merged