Prod 301/is visible and is active campaigns behaviour
gator-labs/chomp pull request #508
Opened 2024-09-16 18:17 UTC by AndrejRadomiljac

✅ Add Linear ID (e.g., `PROD-123`) to PR title to automatically link issue

- Description
- Link to the Linear task: https://linear.app/gator/issue/PROD-301/isvisible-and-isactive-campaigns-behavior
- What are the steps to test that this code is working?
   - On staging DB I've created a Campaign (Andrej test) ID=16. Direct link to /campaigns/16 should result in 404.
   - On staging DB Campaigns Orca (id = 5) and Superteam Vietnam (id=14) are marked as isActive=true and 
      isVisible=false. They should not be displayed on the list but direct links should work /campaigns/5 and /campaigns/14
   - On staging DB Campaign id = 12 is marked as isActive=false and isVisible = true. Direct link should work /campaigns/12  
   and should be visible on the list
   - For the other Campaigns, direct links should work and they should appear on the list 
- Screen shots or recordings for UI changes

2024-09-17 04:06 UTC, marvinmarnold requested changes
Thanks for the clear testing instructions. But one error and one doubt:

- Campaign 5: 404 but should be accessible - https://chomp-j37f77639-gator-labs.vercel.app/campaigns/5
- Campaign 12: The behavior you implemented is what I expect. But not what @Yihwan wrote. Asked for clarity - https://linear.app/gator/issue/PROD-301/isvisible-and-isactive-campaigns-behavior#comment-d0f5e3ae

2024-09-17 09:03 UTC, marvinmarnold commented
> Campaign 12: The behavior you implemented is what I expect. But not what @Yihwan wrote. Asked for clarity - https://linear.app/gator/issue/PROD-301/isvisible-and-isactive-campaigns-behavior#comment-d0f5e3ae

@AndrejRadomiljac, it is confirmed that the behavior you implemented is not currently correct.

2024-09-17 09:13 UTC, AndrejRadomiljac commented
> > Campaign 12: The behavior you implemented is what I expect. But not what @Yihwan wrote. Asked for clarity - https://linear.app/gator/issue/PROD-301/isvisible-and-isactive-campaigns-behavior#comment-d0f5e3ae
> 
> @AndrejRadomiljac, it is confirmed that the behavior you implemented is not currently correct.

@marvinmarnold will fix. Thanks for the feedback.

2024-09-17 20:17 UTC, AndrejRadomiljac commented
> Thanks for the clear testing instructions. But one error and one doubt:
> 
> * Campaign 5: 404 but should be accessible - https://chomp-j37f77639-gator-labs.vercel.app/campaigns/5
> * Campaign 12: The behavior you implemented is what I expect. But not what @Yihwan wrote. Asked for clarity - https://linear.app/gator/issue/PROD-301/isvisible-and-isactive-campaigns-behavior#comment-d0f5e3ae

404 issue. Not sure why it does not work on preview, but I've tested locally and it works as it should. Not sure, why preview behaves in that way, but in the code I cannot see that problem. Here is the screenshot
<img width="1197" alt="Screenshot 2024-09-17 at 22 03 46" src="https://github.com/user-attachments/assets/65abefe0-81b6-4f19-b047-f069b63314fd">

The second issue. There is a clash between tasks here https://linear.app/gator/issue/PROD-293/campaigns-list-campaigns-clean-ups. In the task 293 we said if campaign has zero state we'll disable click on it and remove arrow. In our case, the campaign (12) is marked as isActive = false and isVisible true and it has zero deck state. 

@Yihwan

2024-09-18 07:43 UTC, marvinmarnold commented
>404 issue. Not sure why it does not work on preview,
My bad @AndrejRadomiljac. Looks like I was using the wrong preview link. This is actually working: https://chomp-git-prod-301-isvisible-and-isactive-cam-d51f27-gator-labs.vercel.app/campaigns/5

2024-09-18 16:19 UTC, Yihwan commented on app/campaigns/[id]/page.tsx
> +  console.log("campaign", campaign);
pls remove

2024-09-18 16:20 UTC, Yihwan commented on app/components/CampaignCard/CampaignCard.tsx
> +        {decksToAnswer !== undefined && decksToReveal !== undefined ? (
in the future can we avoid nested ternaries like this because they are hard to read

2024-09-19 06:56 UTC, merged