PROD-295/campaign-detail-cleanup
gator-labs/chomp pull request #514
Opened 2024-09-17 05:58 UTC by yash431garg

- Description
1. Added route back to campaign on specific campaign page
2. Udated campaign image as fallback image and set default to deck image.
- What are the steps to test that this code is working?
1. Redirecting back to campaigns from /campaigns/{campaignsId}
2. Verifying decks images on /campaigns/{campaignsId}

2024-09-17 08:18 UTC, Yihwan commented on app/application/decks/[id]/page.tsx
> +      ) : deck?.questions && deck?.questions?.length > 0 && deck?.deckInfo? (
is this supposed to be a ternary?

2024-09-17 08:19 UTC, Yihwan commented
the preview seems to work as expcted defer cr to @marvinmarnold

2024-09-17 14:56 UTC, marvinmarnold commented on app/application/decks/[id]/page.tsx
> +      ) : deck?.questions && deck?.questions?.length > 0 && deck?.deckInfo? (
Agreed this is weird. This same change appears in other of your recent PRs. Do you have some weird linting/

2024-09-17 16:06 UTC, yash431garg commented on app/campaigns/[id]/page.tsx
> +            imageUrl={deck.imageUrl ? deck.imageUrl : campaign.image}
Will keep in mind from upcoming PRs

2024-09-18 05:27 UTC, marvinmarnold requested changes

2024-09-18 05:34 UTC, closed without merging