PROD-296/deck-info-style-changes
gator-labs/chomp pull request #524
Opened 2024-09-18 05:27 UTC by yash431garg

- Description
Updated deckinfo button to shadcn and screen size
- What are the steps to test that this code is working?
Updated ui and functional go back button.
- Screen shots or recordings for UI changes
![Screenshot 2024-09-17 at 2 39 58 PM](https://github.com/user-attachments/assets/1b36263e-f9af-468b-a9e1-76dabe78ce2d)

2024-09-18 06:31 UTC, marvinmarnold requested changes

2024-09-18 06:31 UTC, marvinmarnold commented on app/screens/DeckScreens/DeckScreen.tsx
> -              Back to homepage
Can't fully test because of: https://linear.app/gator/issue/PROD-323/correct-revealanswer-navigation-from-campaigns

But back button text should change based on how user got here. See instructions here: https://linear.app/gator/issue/PROD-296/deckinfo-card-changes

2024-09-18 06:31 UTC, marvinmarnold commented on app/components/PreviewDeckCard/PreviewDeckCard.tsx
> +        <div className="flex flex-col gap-2 h-[333px]">
Should use min height in case content overflows for some reason

2024-09-18 06:40 UTC, yash431garg commented on app/screens/DeckScreens/DeckScreen.tsx
> -              Back to homepage
Yea, I had a discussion regarding back button with @Yihwan.

Ref: https://linear.app/gator/issue/PROD-296/deckinfo-card-changes#comment-7907f42f

2024-09-18 16:29 UTC, Yihwan requested changes
defer to @gatorthana for design review. 

just based off the screenshot: 
* buttons look short in height, pls dbl check expected btn height 
* deck heading font size does not match mocks 
* deck footer and number of cards should be grouped together at the bottom. see this example when there is no deck image: https://www.figma.com/design/3pZWm9gRbVMnkAfd5zY7GE/Chomp-UI-Shared-Library?node-id=1867-99&node-type=frame&t=ZjLnuaEXrOd7bezM-0
* miscellaneous spacing and font sizes do not seem to match mocks

2024-09-18 17:34 UTC, gatorthana requested changes
<img width="465" alt="Screenshot 2024-09-19 at 1 10 22 AM" src="https://github.com/user-attachments/assets/f44ea4c8-8371-4cbf-9900-9abb8afa1c5d">

Thank you! Requesting a few changs:

1. The title's purple should be AFADEB (secondary)
2. Let's use capitalization convention of first letter caps -- Begin Deck instead of Begin deck.
3. Corner radius of buttons seem less than mocks
4. Progress bar looks thicker than mocks
5. (made this note in figma just now) -- the carrot icon -- this should be a circle, I want to differentiate this from clickable image in the cards.

2024-09-19 04:05 UTC, yash431garg commented
Thanks @Yihwan @gatorthana for the changes request. The requested style changes are not in the scope of this ticket and few of the changes are also part of other ticket. It would be better if we can merge those PRs first and create a follow task. So, that we will not end up doing double work.

2024-09-19 05:32 UTC, marvinmarnold commented
@yash431garg thanks for calling out scope creep. Can you please link to the other issue(s) that you think are better suited for these comments? A merge conflict has also popped up. Can you resolve?

2024-09-19 06:51 UTC, yash431garg commented
> @yash431garg thanks for calling out scope creep. Can you please link to the other issue(s) that you think are better suited for these comments? A merge conflict has also popped up. Can you resolve?

@marvinmarnold the design changes in this ticket will also be relevant here. 
Ref: https://linear.app/gator/issue/PROD-299/update-deckcompletion-screens

2024-09-19 06:54 UTC, marvinmarnold commented
@yash431garg there's conflicts now. Will merge once resolved.

2024-09-19 07:05 UTC, merged

2024-09-19 08:34 UTC, Yihwan commented
sure i'm open to addressing these changes in a separate task ,bu for future reference if there is a mock associated with a task it is assumed that the view be build according to spec, regardless of whether the task explicitly mentions this.

2024-09-19 08:45 UTC, Yihwan commented on app/components/PreviewDeckCard/PreviewDeckCard.tsx
> +          {!!footer && <p className="text-[14px]">{footer}</p>}
why are we using custom font sizes?

2024-09-19 12:05 UTC, yash431garg commented
> sure i'm open to addressing these changes in a separate task ,bu for future reference if there is a mock associated with a task it is assumed that the view be build according to spec, regardless of whether the task explicitly mentions this.

Sure @Yihwan will keep in mind.