PROD-319/rename-campaigns-to-stacks
gator-labs/chomp pull request #556
Opened 2024-09-23 03:22 UTC by danijel-radomiljac

2024-09-23 07:13 UTC, Yihwan reviewed
just want to triple check that we have set up redirects and tested those from campaigns -> stacks to avoid any broken link

2024-09-24 18:13 UTC, marvinmarnold requested changes
- Can you update this to use a path defined here: https://github.com/gator-labs/chomp/blob/main/lib/urls.ts Generally, lets stop hardcoding paths in the app moving forward.
- It looks like /campaigns has been renamed /stacks. But like yihwan said, it would be good to have redirects from /campaigns -> /stacks as well. That way any old links from Breakpoint will keep working.

2024-09-25 13:00 UTC, danijel-radomiljac commented
> * Can you update this to use a path defined here: [`main`/lib/urls.ts](https://github.com/gator-labs/chomp/blob/main/lib/urls.ts?rgh-link-date=2024-09-24T18%3A13%3A29Z) Generally, lets stop hardcoding paths in the app moving forward.
> * It looks like /campaigns has been renamed /stacks. But like yihwan said, it would be good to have redirects from /campaigns -> /stacks as well. That way any old links from Breakpoint will keep working.

Fixed ✅

2024-09-25 13:22 UTC, marvinmarnold requested changes
@danijel-radomiljac I think we need to keep the /campaigns routes that were publicly visible and add hard redirects to /stacks. Let me know if I'm missing some other way that people who see an old QR code to app.chomp.games/campaigns will manage to get redirected to /stacks.

This is in addition to the work in this PR which is good. I'm just saying add a step for redirects.

2024-09-26 21:56 UTC, marvinmarnold requested changes

2024-09-26 21:56 UTC, marvinmarnold commented on next.config.js
> +        source: "/application/campaigns",
Shouldn't this be `/campaigns` -> `/stacks`?

2024-09-26 21:56 UTC, marvinmarnold commented on app/components/CampaignsHeader/CampaignsHeader.tsx
>  const CampaignsHeader: React.FC<CampaignsHeaderProps> = ({
Might be worth going through and renaming the classes to, in order to reduce future tech debt. Eg rename to `StacksHeader` and `StacksHeaderProps`. Also all other campaigns classes in other files.

2024-09-26 21:56 UTC, marvinmarnold commented on app/components/CampaignLeaderboard/CampaignLeaderboard.tsx
> +      <p>Stack Leaderboard</p>
@Yihwan should this be `Stacks` (plural)?

2024-09-30 14:43 UTC, marvinmarnold commented
@danijel-radomiljac conflicts FYI

2024-09-30 21:34 UTC, marvinmarnold commented
Test is failing because migration needs to run

2024-09-30 21:34 UTC, merged