PROD-345: deck completion height issue.
gator-labs/chomp pull request #567
Opened 2024-09-27 08:12 UTC by yash431garg

- Description
Changes no question card height to a fix height 350px with overflow scroll.
- Screen shots or recordings for UI changes
![Screenshot 2024-09-27 at 1 33 39 PM](https://github.com/user-attachments/assets/7c0f209a-b2c9-4179-959a-42d42fdb53e2)

2024-09-30 14:44 UTC, marvinmarnold commented
@neel-ds can you review

2024-09-30 14:47 UTC, marvinmarnold requested changes

2024-09-30 14:47 UTC, marvinmarnold commented on app/components/NoQuestionsCard/NoQuestionsCard.tsx
> +      <div className="bg-gray-700 h-[350px] w-full max-w-[480px] rounded-xl pt-6 pl-4 pr-4 flex flex-col justify-between border border-gray-500 text-white relative mb-[4px] overflow-scroll">
Why did you just change NoQuestionsCard? I think all of the deck completion screens are in scope.

2024-09-30 16:00 UTC, neel-ds commented
@yash431garg Apply same changes to following files:
https://github.com/gator-labs/chomp/blob/5b302c1e599ab031d8349d4474efb6991fa063f5/app/components/PreviewDeckCard/PreviewDeckCard.tsx#L27

https://github.com/gator-labs/chomp/blob/5b302c1e599ab031d8349d4474efb6991fa063f5/app/components/QuestionCard/QuestionCard.tsx#L75

2024-10-01 13:47 UTC, yash431garg commented
> @yash431garg Apply same changes to following files:
> 
> https://github.com/gator-labs/chomp/blob/5b302c1e599ab031d8349d4474efb6991fa063f5/app/components/PreviewDeckCard/PreviewDeckCard.tsx#L27
> 
> https://github.com/gator-labs/chomp/blob/5b302c1e599ab031d8349d4474efb6991fa063f5/app/components/QuestionCard/QuestionCard.tsx#L75

Thanks @neel-ds, I just added those changes.

2024-10-01 13:48 UTC, yash431garg commented on app/components/NoQuestionsCard/NoQuestionsCard.tsx
> +      <div className="bg-gray-700 h-[350px] w-full max-w-[480px] rounded-xl pt-6 pl-4 pr-4 flex flex-col justify-between border border-gray-500 text-white relative mb-[4px] overflow-scroll">
Just added them. I thought only deck completion card was in the scope.

2024-10-01 13:55 UTC, neel-ds approved these changes

2024-10-01 14:48 UTC, merged