PROD-318/dont-show-question-to-reveal-with-too-few-answers-for-calculating-the
gator-labs/chomp pull request #573
Opened 2024-10-01 13:23 UTC by danijel-radomiljac

2024-10-02 17:07 UTC, AndrejRadomiljac submitted a review, later dismissed

2024-10-02 23:54 UTC, marvinmarnold requested changes
Blocker: Can you add this env var to the README and .env.example

Not blocker: Refactoring

2024-10-02 23:54 UTC, marvinmarnold commented on app/stacks/[id]/page.tsx
> +              stack.deck
Can you refactor this? At the minimum, do this calculation above, before the HTML rendering and store result in var. Then reference variable here. 

Even better would be to define a utility function for this logic.

2024-10-02 23:54 UTC, marvinmarnold commented on app/queries/history.ts
>      (question) =>
Can this repeated logic be refactored?

2024-10-03 14:21 UTC, marvinmarnold approved these changes

2024-10-04 07:53 UTC, merged