PROD-364 Add UTM attributes in mixpanel
gator-labs/chomp pull request #581
Opened 2024-10-03 12:40 UTC by neel-ds

- Description
Add UTM parameters in mixpanel track requests
- What are the steps to test that this code is working?
Add utm params in the url and verify the event in mixpanel. For e.g I added `utm_source` in an event
- Screen shots or recordings for UI changes
![Screenshot 2024-10-03 at 5 54 59 PM](https://github.com/user-attachments/assets/6ce98171-ea71-47f0-932b-1157df714889)

2024-10-03 14:39 UTC, marvinmarnold requested changes
The [docs](https://docs.mixpanel.com/docs/tracking-best-practices/server-side-best-practices#tracking-utms-and-referrer) list a few other UTM fields: `utm_content` and `utm_term`. Any reason you didn't include those?

2024-10-03 16:01 UTC, neel-ds commented
> The [docs](https://docs.mixpanel.com/docs/tracking-best-practices/server-side-best-practices#tracking-utms-and-referrer) list a few other UTM fields: `utm_content` and `utm_term`. Any reason you didn't include those?

I have added those attributes now. ✅

2024-10-03 21:00 UTC, marvinmarnold submitted a review, later dismissed

2024-10-04 09:02 UTC, Yihwan commented on lib/mixpanel.ts
> +    $utm_content: urlParams.get("utm_content") || undefined,
actually scond thought, let's just keep to officially supported utms for now and add the arbitrary ones if needed.

2024-10-04 09:18 UTC, Yihwan requested changes
need to preserve utm attribution on route changes as noted here https://linear.app/gator/issue/PROD-364/add-utm-attribution-to-mixpanel#comment-29acb1fc

2024-10-14 11:47 UTC, neel-ds commented
This PR adds initial_utm and last_utm tracking facilities in mixpanel route using Vercel KV. 

cc: @marvinmarnold @Yihwan 
![Screenshot 2024-10-14 at 4 49 15 PM](https://github.com/user-attachments/assets/28a6760c-b3cb-4e86-a65c-73b81496e7e0)

2024-10-14 14:57 UTC, marvinmarnold requested changes
There's also some important follow up: https://linear.app/gator/issue/PROD-364/add-utm-attribution-to-mixpanel

2024-10-14 14:57 UTC, marvinmarnold commented on app/api/mixpanel/route.ts
> +        initialUtm = initialUtm.utm_source ? initialUtm : utmParams;
How about: `Object.keys(initialUtm).length > 0 ? initialUtm : utmParams;`

2024-10-14 14:57 UTC, marvinmarnold commented on app/api/mixpanel/route.ts
> +        lastUtm = { ...lastUtm, ...utmParams };
`lastUtm = hasNewUtmParams ?  utmParams : lastUtm` because we don't want to mix UTM params from different events.

2024-10-15 12:20 UTC, neel-ds commented on app/api/mixpanel/route.ts
> +        initialUtm = initialUtm.utm_source ? initialUtm : utmParams;
Good catch, thank you!

2024-10-15 12:21 UTC, neel-ds commented on app/api/mixpanel/route.ts
> +        lastUtm = { ...lastUtm, ...utmParams };
yes, make sense

2024-10-15 17:14 UTC, marvinmarnold requested changes
Please also add test cases.

2024-10-17 15:50 UTC, Yihwan approved these changes
thanks confirmed working. out of curiosity dyk why last_utm_source and Initial UTM Source are formatted differently in mixpanel? is it something that mixpanel does under the hood?

2024-10-17 17:49 UTC, merged

2024-10-17 17:56 UTC, neel-ds commented
> thanks confirmed working. out of curiosity dyk why last_utm_source and Initial UTM Source are formatted differently in mixpanel? is it something that mixpanel does under the hood?

To know the origin of first lead and track last touch of a user. It was proposed by Marvin and more details can be found in Linear issue comments.