PROD-382/add-streaks
gator-labs/chomp pull request #590
Opened 2024-10-08 11:32 UTC by danijel-radomiljac

Preview video: 

https://github.com/user-attachments/assets/2cdc3c78-6754-49e8-a4ff-6c175e14fe22

@marvinmarnold @Yihwan Since we are querying longest streak in a new way, can we delete a Streak table from database?

2024-10-08 16:26 UTC, marvinmarnold requested changes

2024-10-08 16:26 UTC, marvinmarnold commented on app/queries/home.ts
> +async function queryUsersLongestStreak(userId: string): Promise<number> {
Can you add tests. See reference test implementation: https://github.com/gator-labs/chomp/pull/579

2024-10-09 09:05 UTC, danijel-radomiljac commented on app/queries/home.ts
> +async function queryUsersLongestStreak(userId: string): Promise<number> {
I will wait for that pr to be merged first. Because there are some test setup changes.

2024-10-09 09:22 UTC, yash431garg commented on app/queries/home.ts
> +async function queryUsersLongestStreak(userId: string): Promise<number> {
Will try to merge it asap.

2024-10-09 13:59 UTC, marvinmarnold commented on app/queries/home.ts
> +async function queryUsersLongestStreak(userId: string): Promise<number> {
I'm OK to drop Streak from DB if not being used.

2024-10-11 04:41 UTC, gatorthana approved these changes
Looks good to me!

2024-10-14 14:06 UTC, merged