PROD-381/add-bonk-claimed-and-cards-revealed
gator-labs/chomp pull request #591
Opened 2024-10-08 13:45 UTC by danijel-radomiljac

![Screenshot 2024-10-08 at 15 43 51](https://github.com/user-attachments/assets/9df97a20-6c6a-41f9-8c9d-7553c3c78c7d)

@gatorthana I need a icon names for bonk claimed and cards revealed.

2024-10-08 16:27 UTC, marvinmarnold requested changes

2024-10-08 16:27 UTC, marvinmarnold commented on app/queries/home.ts
> +async function queryUsersTotalClaimedAmount(userId: string): Promise<number> {
Please add tests.

2024-10-09 09:06 UTC, danijel-radomiljac commented on app/queries/home.ts
> +async function queryUsersTotalClaimedAmount(userId: string): Promise<number> {
I will wait for https://github.com/gator-labs/chomp/pull/579 PR to be merged. Because there are some setup test changes.

2024-10-09 09:22 UTC, yash431garg commented on app/queries/home.ts
> +async function queryUsersTotalClaimedAmount(userId: string): Promise<number> {
Will try to merge it asap.

2024-10-11 04:44 UTC, gatorthana commented
@danijel-radomiljac the BONK icon and the CARD icons were custom ones because I couldn't find a suitable one from Lucide library. @Yihwan for custom icons, would that break things or add too much complications?

2024-10-13 15:01 UTC, gatorthana commented
![Bonk Icon](https://github.com/user-attachments/assets/3c91d0c4-e47d-411d-98d1-80280246981c)
![card](https://github.com/user-attachments/assets/6f0b6f8e-4b36-4e54-9f73-96d523f0f47d)

@danijel-radomiljac here are the SVG for the 2 custom icons, lmk if these are okay!

2024-10-14 14:07 UTC, marvinmarnold commented
@danijel-radomiljac conflicts

@neel-ds @yash431garg @AndrejRadomiljac review please

2024-10-15 13:06 UTC, merged