PROD-383: Sentry invariant expected app router to be mounted
gator-labs/chomp pull request #592
Opened 2024-10-09 09:22 UTC by yash431garg

- Description
Previously because we had useRouter in our error boundary and global error file catches the error from Root Layout which is out of next context causing this error sentry invariant expected app router to be mounted.
- What are the steps to test that this code is working?
Rendering global-error and error boundary in production properly.
- Screen shots or recordings for UI changes
N/A

2024-10-10 00:08 UTC, marvinmarnold requested changes

2024-10-10 00:08 UTC, marvinmarnold commented on app/components/ErrorBoundary/ErrorBoundary.tsx
> +          variant="outline"
Why are you removing the `Link`? This is unrelated to removing useRouter. And there's another instance of `Link` above in the code that wasn't removed.

2024-10-10 06:56 UTC, yash431garg commented on app/components/ErrorBoundary/ErrorBoundary.tsx
> +          variant="outline"
I have the Link because we already have a button and instead of wrapping it with a Link I thought of just doing from the onClick method with using router.

2024-10-10 09:48 UTC, danijel-radomiljac submitted a review, later dismissed

2024-10-10 20:58 UTC, marvinmarnold requested changes

2024-10-10 20:58 UTC, marvinmarnold commented on app/components/ErrorBoundary/ErrorBoundary.tsx
> +          variant="outline"
Link doesn't use `useRouter` though. And like I said, line 43 still uses Link, so I don't get why change it just here.

More importantly, do you really want to link to `/failed`?

2024-10-11 02:08 UTC, yash431garg commented on app/components/ErrorBoundary/ErrorBoundary.tsx
> +          variant="outline"
Sorry, I don't want to route to /failed it is a mistake I change to to home path.

2024-10-11 11:24 UTC, marvinmarnold approved these changes

2024-10-14 14:08 UTC, merged