PROD-379/unable-to-access-stack
gator-labs/chomp pull request #593
Opened 2024-10-09 09:44 UTC by danijel-radomiljac

2024-10-09 12:42 UTC, yash431garg approved these changes

2024-10-10 00:05 UTC, marvinmarnold requested changes
@danijel-radomiljac I created an empty deck and added it to a stack [here](https://chomp-git-prod-379-unable-to-access-stack-gator-labs.vercel.app/stacks/19). But when viewing from /stacks, I'm not able to click into the deck. Direct link does work as expected.
![Screenshot 2024-10-09 at 7 04 53 PM](https://github.com/user-attachments/assets/cc5c6294-12bc-43c3-bcfb-cce9c29825e7)

2024-10-10 00:05 UTC, marvinmarnold commented on app/components/StackCard/StackCard.tsx
> +        {decksToAnswer !== undefined &&
Ideally define this in a variable above

2024-10-10 22:38 UTC, marvinmarnold approved these changes

2024-10-11 08:19 UTC, merged