PROD-384 Resolve load failed issue
gator-labs/chomp pull request #597
Opened 2024-10-13 08:48 UTC by neel-ds

### Description

This issue was addressed in #583 and console errors sentry integration was added to assess such an issue. Load Failed errors occur when Fetch API calls fail. It usually happens on Apple devices. It’s not a disruptive error, but it gets triggered when the user opens the login modal and mixpanel returns 500. 

I have updated the mixpanel route to always return 200 and disable console errors integration for developement environment to avoid unnecessary notifications in the Slack channel.

### What are the steps to test that this code is working?

Mixpanel will always work technically and no more spam in sentry notifications.
![Screenshot 2024-10-13 at 2 16 14 PM](https://github.com/user-attachments/assets/be574360-4b76-473d-a985-be2c2b29c36a)

### Screen shots or recordings for UI changes
NA

2024-10-14 15:00 UTC, marvinmarnold requested changes

2024-10-14 15:00 UTC, marvinmarnold commented on app/api/mixpanel/route.ts
> +    console.log("[Mixpanel]", error);
Can you make this error level log? Based `sentry.server.config.ts`, will a Sentry event be triggered if this is updated to an error level log?

2024-10-15 06:55 UTC, danijel-radomiljac approved these changes

2024-10-15 11:59 UTC, neel-ds commented on app/api/mixpanel/route.ts
> +    console.log("[Mixpanel]", error);
yes, sentry console integration will log this error

2024-10-15 13:09 UTC, merged