Prod 393: All time leaderboard
gator-labs/chomp pull request #599
Opened 2024-10-14 11:48 UTC by yash431garg

- Description
All time leaderboard page and tab
- What are the steps to test that this code is working?
A new all time leaderboard tab on leaderbaord page which will navigate to all time leaderboard page
- Screen shots or recordings for UI changes
<img width="423" alt="Screenshot 2024-10-14 at 5 18 17 PM" src="https://github.com/user-attachments/assets/60128009-90a4-44ab-8c50-428c63c55111">

2024-10-14 11:49 UTC, yash431garg commented
Before merge we need to may be change the icon for all time tab. 

cc: @marvinmarnold @Yihwan

2024-10-14 12:17 UTC, danijel-radomiljac commented on app/application/leaderboard/all-time/page.tsx
> +  if (!user) redirect("login");
/login should go

2024-10-14 13:29 UTC, yash431garg commented on app/application/leaderboard/all-time/page.tsx
> +  if (!user) redirect("login");
Just added it in the same pr @danijel-radomiljac

2024-10-15 07:42 UTC, gatorthana commented
@yash431garg here you go!

https://www.figma.com/design/3pZWm9gRbVMnkAfd5zY7GE/Chomp-UI-Shared-Library?node-id=2452-357&node-type=canvas&t=XnUaUZH5spt90Y6W-11

2024-10-15 08:55 UTC, yash431garg commented on app/actions/leaderboard.ts
> +  variant: "weekly" | "daily" | "stack" | "all-time";
Sure,

2024-10-15 13:02 UTC, marvinmarnold commented
@yash431garg test is failing btw

2024-10-15 15:43 UTC, yash431garg commented
> @yash431garg test is failing btw

Yea, it is failing because rpc url is missing in workflow secret keys. I will check if I can mock this otherwise we can add that key.

2024-10-15 17:28 UTC, marvinmarnold requested changes
Update workflow so that env supplied to test: https://github.com/gator-labs/chomp/blob/5ff2ade4099aec6b5b817380072f9778829f0999/.github/workflows/test.yml#L25

2024-10-15 17:46 UTC, marvinmarnold commented on __tests__/actions/get_alltime-leaderboard.test.ts
> +describe("Get All-time leaderboard data", () => {
jest.setTimeout(30_000)

2024-10-15 17:46 UTC, marvinmarnold commented on __tests__/actions/get_alltime-leaderboard.test.ts
> +describe("Get All-time leaderboard data", () => {
before describe

2024-10-16 17:10 UTC, danijel-radomiljac approved these changes

2024-10-16 17:10 UTC, danijel-radomiljac approved these changes

2024-10-17 05:42 UTC, merged