PROD-376: : Track page-loaded in mixpanel
gator-labs/chomp pull request #607
Opened 2024-10-16 10:44 UTC by yash431garg

- Description
Track page load event on mixpanel with event name PageView and event properties in mixpanel properties URL_PATH, URL_SEARCH and hostname
- What are the steps to test that this code is working?
Verifying PageView events in Mixpanel properties.
- Screen shots or recordings for UI changes
N/A

2024-10-16 10:51 UTC, neel-ds approved these changes

2024-10-16 17:10 UTC, danijel-radomiljac approved these changes

2024-10-16 20:15 UTC, marvinmarnold requested changes

2024-10-17 06:13 UTC, yash431garg commented on app/constants/tracking.ts
> +  URL_PATH: "URL PATH",
Thanks for pointing out!

2024-10-17 06:13 UTC, yash431garg commented on app/constants/tracking.ts
> +  URL_PATH: "URL PATH",
Thanks for pointing out!

2024-10-21 09:00 UTC, danijel-radomiljac submitted a review, later dismissed
LGTM ✅

2024-10-22 03:17 UTC, marvinmarnold approved these changes

2024-10-22 05:48 UTC, neel-ds approved these changes

2024-10-22 05:49 UTC, merged