PROD-352: configured eslint, prettier and husky
gator-labs/chomp pull request #613
Opened 2024-10-18 08:23 UTC by yash431garg

- Description
Integrated eslint for lint error includes tslint, import and hooks warning. Added prettier with formatting rules and husky for precommit check
- What are the steps to test that this code is working?
No functional changes
- Screen shots or recordings for UI changes
N/A

2024-10-18 09:36 UTC, neel-ds requested changes
Kindly add more files and folders in `prettierignore` as mentioned below and revert the changes of same files or folders. I also found line breaks between imports in almost every files. What's the purpose behind it? Please remove that rule unless there is convention

2024-10-18 09:36 UTC, neel-ds commented on .prettierignore
> +
You can add more folders and files in ignore like:
- all files / folders starting with .
- yarn.lock
- postgres-data
- README files

2024-10-18 09:36 UTC, neel-ds commented on .storybook/README.md
> +`yarn run storybook`
This change should be reverted once you follow up on `prettierignore` review

2024-10-18 09:36 UTC, neel-ds commented on app/components/Icons/DeckIcon.tsx
> -  fill = "#fff",
Can we keep this fill prop unless by default is #fff? Not sure if it was intentional

2024-10-21 14:01 UTC, yash431garg commented
> Kindly add more files and folders in `prettierignore` as mentioned below and revert the changes of same files or folders. I also found line breaks between imports in almost every files. What's the purpose behind it? Please remove that rule unless there is convention

The reason behind line breaks in import was to separate packages which are external and internal components.

2024-10-21 14:24 UTC, yash431garg commented on app/components/Icons/DeckIcon.tsx
> -  fill = "#fff",
It was not used here that why comes to property of unused vars.

2024-10-22 03:21 UTC, marvinmarnold commented on .husky/pre-commit
> +#!/bin/sh
Will all of these also be run when a PR is open?

2024-10-22 03:55 UTC, yash431garg commented on .husky/pre-commit
> +#!/bin/sh
No, It will run after we commits and will block the commit if there is some issue.

2024-10-22 04:25 UTC, yash431garg commented on .husky/pre-commit
> +#!/bin/sh
Sure, I will add this in the workflow.

2024-10-22 13:25 UTC, marvinmarnold commented
@neel-ds can you please re-review?

2024-10-22 13:25 UTC, marvinmarnold approved these changes

2024-10-22 13:26 UTC, marvinmarnold submitted a review, later dismissed

2024-10-22 13:35 UTC, neel-ds commented on .prettierignore
> +
To ignore README files, `*.md` use this instead of README*

2024-10-22 15:23 UTC, neel-ds submitted a review, later dismissed

2024-10-23 20:05 UTC, marvinmarnold approved these changes

2024-10-24 13:57 UTC, neel-ds approved these changes

2024-10-24 16:07 UTC, marvinmarnold approved these changes

2024-10-25 16:21 UTC, merged