PROD-420/share-claim-all
gator-labs/chomp pull request #624
Opened 2024-10-23 09:49 UTC by danijel-radomiljac

2024-10-23 19:51 UTC, marvinmarnold requested changes
Looks good. Very thorough to add the encryption, nice. 

You followed the issue requirements well, but I have some new thoughts.

2024-10-23 19:51 UTC, marvinmarnold commented on app/a/[txHash]/page.tsx
> +  redirect(
This is correct according to the issue, but should be updated.

Some of these values will be different for links that are manually copied, vs ones that are shared via twitter.

I think utm_campaign and utm_content will be the same in both cases and can be appended here.

utm_source and utm_medium will need to be supplied on the link shown to users. @Yihwan what values do you want to use for the manual link copy case? 

@danijel-radomiljac one final thought is that it may be possible to infer Twitter shares via some other mechanism. For example, maybe we can look for the HTTP referrer. In that case, we could continue providing links without any UTM and add here like you are doing now.

2024-10-23 19:51 UTC, marvinmarnold commented on app/api/og/share-claim-all/route.tsx
> +  const encryptedHash = searchParams.get('txHash');
Lets change the param name to encryptedTxHash for clarity

2024-10-23 19:51 UTC, marvinmarnold commented on lib/urls.ts
> +export const getOgShareClaimAllPath = (txHash: string) =>
Change params to encryptedTxHash

2024-10-23 19:51 UTC, marvinmarnold commented on lib/urls.ts
> +  const encryptedTxHash = encrypt(txHash);
These hashes will be long. How about we take the first X characters and encrypt just those?

2024-10-23 19:51 UTC, marvinmarnold commented on app/constants/tracking.ts
> +  SHARE_DIALOG_LOADED: 'ShareDialogLoaded',
I think we should change all these to ShareAllDiaglogLoaded, etc. To disambiguate from the share single flow. Could also use the same event for both all and single, but supply a param to disambiguate.

2024-10-24 09:02 UTC, danijel-radomiljac commented on app/a/[txHash]/page.tsx
> +  redirect(
Hmm I am not actually sure what I need to change

2024-10-24 16:21 UTC, marvinmarnold commented on app/a/[txHash]/page.tsx
> +  redirect(
Yes that was rather wordy. 

1. Always append: utm_campaign=app_share&utm_content=claim_all
2. Check for [HTTP referrer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer).
3. If referrer = twitter, then append utm_source=x&utm_medium=social
4. If referrer is something els, then append utm_source=REFERRER and utm_medium=manual_link

But I'm not sure about the values to use for step #4. @Yihwan may suggest other values.

2024-10-25 17:22 UTC, yash431garg commented on app/actions/claim.ts
> +  console.log('claim questions fired');
Is this console intentional?

2024-10-25 17:28 UTC, yash431garg commented on app/actions/claim.ts
> +  console.log('claim questions fired');
Is this console intentional?

2024-10-25 17:28 UTC, yash431garg commented on app/api/og/share-claim-all/route.tsx
> +      height: 630,
I think you need to change the dimensions here to maintain image quality. It is W: 622 & H: 418 in figma

2024-10-25 17:28 UTC, yash431garg commented on app/utils/crypto-js.ts
Can you add comments in this file regarding the functions?

2024-10-28 09:36 UTC, danijel-radomiljac commented on app/actions/claim.ts
> +  console.log('claim questions fired');
yes

2024-10-28 09:36 UTC, danijel-radomiljac commented on app/api/og/share-claim-all/route.tsx
> +      height: 630,
og image needs to be 1200x630

2024-10-28 09:37 UTC, danijel-radomiljac commented on app/utils/crypto-js.ts
it is just basic encryption and decryption

2024-10-29 00:13 UTC, marvinmarnold commented on app/api/og/share-claim-all/route.tsx
> +      height: 630,
Why does it have to be that size? I see that it is recommended: https://vercel.com/docs/functions/og-image-generation#technical-details

2024-10-29 00:29 UTC, marvinmarnold requested changes
Just tested. Pretty smooth.

- Can we decrease the encrypted hash to 10 characters? How long is the unencrypted text in that case? Links are still long: https://chomp-jdteee2lr-gator-labs.vercel.app/a/VTJGc2RHVmtYMStzT3M0em9aUHA4ZXpvazR6WG5rd0FkLytYSkQ5OWd0Zz0
- Waiting on clarity on image size issue

2024-10-29 09:27 UTC, danijel-radomiljac commented
> Just tested. Pretty smooth.
> 
> * Can we decrease the encrypted hash to 10 characters? How long is the unencrypted text in that case? Links are still long: [chomp-jdteee2lr-gator-labs.vercel.app/a/VTJGc2RHVmtYMStzT3M0em9aUHA4ZXpvazR6WG5rd0FkLytYSkQ5OWd0Zz0](https://chomp-jdteee2lr-gator-labs.vercel.app/a/VTJGc2RHVmtYMStzT3M0em9aUHA4ZXpvazR6WG5rd0FkLytYSkQ5OWd0Zz0)
> * Waiting on clarity on image size issue

the shortes encryption result is 50chars.

Yea it is just the recommendation to keep 1200x630 dimension. Honestly it looks ok to me. 
![Screenshot 2024-10-28 at 12 24 26](https://github.com/user-attachments/assets/e8821093-ecf3-456d-b6f7-40060ba512e2)

2024-11-04 23:25 UTC, marvinmarnold requested changes
Blocked by:
- https://linear.app/gator/issue/PROD-420/share-claim-all#comment-6db3f238
- https://linear.app/gator/issue/PROD-420/share-claim-all#comment-e622798f

2024-11-05 18:55 UTC, merged