PROD-423: added fee estimation for bonk claim transaction
gator-labs/chomp pull request #629
Opened 2024-10-28 08:08 UTC by yash431garg

- Description
Added priority fees, compute unit calculate logic and retry transaction in bonk claim
- What are the steps to test that this code is working?
Greater chances of successful claim after reveal
- Screen shots or recordings for UI changes
N/A

2024-10-29 01:06 UTC, marvinmarnold requested changes
I was surprised to see this approach differ so much from the existing reveal code. Was this pattern inspired by some source? gpt?

If you think this is bettter than the reveal code, should we update that code too?

2024-10-29 01:06 UTC, marvinmarnold commented on app/utils/bonk.ts
> +      return await pollTransactionConfirmation(txtSig);
I think this could lead to us sending multiple transactions. In a case where the tx succeeds, but the confirmations fails for some reason.

In that case, a special Sentry error could be triggered with the tx signature. User should see an error message that support is looking into it. We can manually send funds if it looks like tx really failed.

2024-10-29 01:06 UTC, marvinmarnold commented on app/utils/bonk.ts
> +  while (retryCount <= maxRetries) {
Consider using a 3rd party library or abstracting this code into a utility method if it comes up a lot.

eg https://www.npmjs.com/package/p-retry

2024-10-29 10:18 UTC, yash431garg commented on app/utils/bonk.ts
> +  instructions.unshift(computeBudgetIx);
This will update the dynamic generated instructions for the compute unit

2024-10-29 10:22 UTC, yash431garg commented on app/utils/bonk.ts
> +  const unitsConsumed = await getComputeUnits(
It was suggested on the official docs to calculate compute unit dynamically as well.

2024-10-29 10:23 UTC, yash431garg commented on app/utils/bonk.ts
> +      return await pollTransactionConfirmation(txtSig);
I will look into it.

2024-10-29 11:37 UTC, yash431garg commented
> I was surprised to see this approach differ so much from the existing reveal code. Was this pattern inspired by some source? gpt?
> 
> If you think this is bettter than the reveal code, should we update that code too?

It was inspired by official helius, solana and quicknode docs.

2024-10-29 12:21 UTC, yash431garg commented on app/utils/bonk.ts
> +  while (retryCount <= maxRetries) {
Thansks, for the suggestion!

2024-10-30 17:02 UTC, marvinmarnold commented on app/utils/bonk.ts
> +  const unitsConsumed = await getComputeUnits(
I still think this should be removed. Use hardcoded value instead.

2024-10-31 10:57 UTC, neel-ds submitted a review, later dismissed

2024-11-04 20:14 UTC, marvinmarnold requested changes

2024-11-04 20:14 UTC, marvinmarnold commented on app/utils/bonk.ts
>    VersionedTransaction,
Can we rename this file while at it? Maybe `claim.ts`?

2024-11-04 20:14 UTC, marvinmarnold commented on app/utils/bonk.ts
> +    microLamports: estimateFee?.result?.priorityFeeLevels?.high || 5000,
Where are you getting 5,000 from here? Looking at some recent burns (where we do dynamically calculate price), prices range from 50,000 - 200,000.

https://solscan.io/tx/2gMj99sRHNh1n9cwxFu1nN2MKnHT1vZep9NLmW4Vcm8UbEVTtna2AE4UNs5FGDLSQbBwaKn7obEbjvJQz4eqxHpj

https://solscan.io/tx/2Tu1j4CCgt3zSMQEcELLtun5vQS6uUnmwRJccwDU4U5H4HVqYHsiVEG1tHF8UDshMJGpeRa3bcB5gzywCmBnu9Yv

https://solscan.io/tx/3FfzRhSeWHXgzPFkCC3BeWu2Qxnw7t3evMrfcw1Ci546WmWJDnUeDvYXYjJbWkyn1Ga8KCpdD4h7nKgqnD3CAKfE

2024-11-04 20:14 UTC, marvinmarnold commented on app/utils/bonk.ts
> +  const computeUnitFix = 5000;
Should be 4794.

2024-11-04 20:14 UTC, marvinmarnold commented on app/utils/bonk.ts
> +    units: computeUnitFix * 1.1,
Maybe we can get rid of the buffer (1.1). The units never seems to change.

2024-11-05 04:22 UTC, yash431garg commented on app/actions/leaderboard.ts
> +        createdAt: {
Yea, this is an old pr that's why we still have that formatting related changes here.

2024-11-05 04:24 UTC, yash431garg commented on app/queries/getComputeUnitEstimate.ts
> +export const getComputeUnits = async (
Sure, I thought that it can be used in future but will remove it for now.

2024-11-05 05:21 UTC, yash431garg commented on app/utils/bonk.ts
>    VersionedTransaction,
Sure,

2024-11-05 05:58 UTC, yash431garg commented on app/utils/bonk.ts
> +    microLamports: estimateFee?.result?.priorityFeeLevels?.high || 5000,
Fair, I also update the estimate to 50k if estimateFee query fails

2024-11-05 06:15 UTC, yash431garg commented on app/utils/bonk.ts
> +    units: computeUnitFix * 1.1,
Adding compute unit in exact number cause the transaction to fail that's why a buffer is added.

2024-11-05 06:15 UTC, yash431garg commented on app/utils/bonk.ts
> +  const computeUnitFix = 5000;
Done

2024-11-05 15:43 UTC, marvinmarnold commented on app/utils/claim.ts
> +  await CONNECTION.confirmTransaction(
What happens if tx goes through but can't be confirmed for some reason? What will the user see?

2024-11-05 15:45 UTC, marvinmarnold submitted a review, later dismissed

2024-11-05 15:45 UTC, marvinmarnold commented on app/utils/claim.ts
> +  const computeUnitFix = 4794;
Add a comment about where this number comes from

2024-11-05 15:45 UTC, marvinmarnold commented on app/utils/claim.ts
> +    microLamports: estimateFee?.result?.priorityFeeLevels?.high || 50000,
Add comment about where 50000 comes from

2024-11-05 16:16 UTC, marvinmarnold commented on app/utils/claim.ts
> +    microLamports: estimateFee?.result?.priorityFeeLevels?.high || 50000,
Make this a variable and reuse in burn

2024-11-05 16:18 UTC, marvinmarnold commented on app/utils/claim.ts
> +    units: computeUnitFix * 1.1,
Can you leave a comment that this fails unless there is buffer

2024-11-05 17:59 UTC, yash431garg commented on app/utils/claim.ts
> +  await CONNECTION.confirmTransaction(
This https://github.com/gator-labs/chomp/blob/814ff3a81e597873660992a70dfc9588d01a036a/app/components/History/TotalRewardsClaimAll/TotalRewardsClaimAll.tsx#L56

2024-11-05 19:08 UTC, yash431garg commented on app/utils/claim.ts
> +  await CONNECTION.confirmTransaction(
![Uploading Screenshot 2024-11-06 at 12.38.06 AM.png…]()

2024-11-05 19:15 UTC, marvinmarnold commented on app/utils/claim.ts
> +  await CONNECTION.confirmTransaction(
image does not load

2024-11-05 19:17 UTC, marvinmarnold commented on app/utils/solana.ts
> +  const computeUnitFix = 4794;
```suggestion
  const computeUnitFix = 4960;
```

2024-11-05 19:18 UTC, yash431garg commented on app/utils/claim.ts
> +  await CONNECTION.confirmTransaction(
![Uploading Screenshot 2024-11-06 at 12.38.06 AM.png…]()

2024-11-05 19:18 UTC, yash431garg commented
![Uploading Screenshot 2024-11-06 at 12.38.06 AM.png…]()

2024-11-05 19:24 UTC, yash431garg commented on app/utils/claim.ts
> +  await CONNECTION.confirmTransaction(
User will see Transaction Failed! Please try again. If this issue keep happening please, let us know on telegram.

2024-11-05 19:38 UTC, merged