Prodl 422/error recovery failed claim
gator-labs/chomp pull request #630
Opened 2024-10-28 12:15 UTC by yash431garg

- Description
Previously if claim fails user isn't able to claim again but his bonk is already burned after this change user will be able do claim again incase it fails.
- What are the steps to test that this code is working?
Error through if sendBonk failed and not user should be able to claim again if it fails
- Screen shots or recordings for UI changes
<img width="1280" alt="Screenshot 2024-10-28 at 5 43 07 PM" src="https://github.com/user-attachments/assets/d7af22f8-6e6a-47be-9fcf-627b9dd7549a">

2024-10-29 09:44 UTC, danijel-radomiljac submitted a review, later dismissed

2024-10-29 13:49 UTC, marvinmarnold requested changes
Ah I forgot to submit this comment.

2024-10-30 03:08 UTC, marvinmarnold commented on app/providers/ToastProvider.tsx
> +  const parts = message.split(TELEGRAM_LINK_MARKER);
I still don't love this code. At the minimum, we also need comments here and in the error definition to explain the format.

After looking at the code more closely, we could update `errorToastLayout` to accept an additional optional param.

```
interface IToastExtraConfig= {}

interface IToastTelegramConfig extends IToastExtraConfig {
   type: 'telegram_link',
   text: string
}

errorToastLayout = (message: string, description?: string, extraConfig?: IToastExtraConfig)
```

Just one possible implementation..

2024-10-30 06:32 UTC, yash431garg commented on app/providers/ToastProvider.tsx
> +  const parts = message.split(TELEGRAM_LINK_MARKER);
Thanks, I spent a little more time on it and updated the ToastProvider so that it can now accept ReactNode and now we don't need to keep that implementation.

2024-10-30 16:40 UTC, merged