PROD-408 Routes for notification and bot user
gator-labs/chomp pull request #633
Opened 2024-10-29 21:22 UTC by neel-ds

- Description
The PR adds two routes for notification handling and bot user handling. It includes schema changes required to maintain subscriber property. 

- What are the steps to test that this code is working?
Test the bot with /resubscribe and /unsubscribe commands

- Screen shots or recordings for UI changes
<img width="642" alt="Screenshot 2024-10-30 at 2 36 53 AM" src="https://github.com/user-attachments/assets/901eccd0-6e99-49af-ba52-531d710bd3cf">

2024-11-01 17:19 UTC, marvinmarnold requested changes

2024-11-01 17:19 UTC, marvinmarnold commented on prisma/schema.prisma
> +  isSubscriber                Boolean                       @default(false)
This variable name is not specific enough. Can you rename to `isBotSubscriber` or similar.

2024-11-01 17:19 UTC, marvinmarnold commented on app/api/notification/route.ts
> +  ➤ GET METHOD: FETCHES SUBSCRIBED USERS
Let's split this up into two files. Paths should be more descriptive, eg `app/api/users/getSubscribedUsers/route.ts`

2024-11-01 17:19 UTC, marvinmarnold commented on app/api/notification/route.ts
> +export async function GET() {
All API methods should have tests

2024-11-01 17:19 UTC, marvinmarnold commented on app/api/notification/route.ts
> +export async function POST(request: Request) {
Unnecessary? Can't the user#GET route below be used for this?

2024-11-04 19:48 UTC, marvinmarnold requested changes

2024-11-04 19:48 UTC, marvinmarnold commented on __tests__/api/user/createUserByTelegramId/route.test.ts
> +const BASE_URL = process.env.VERCEL_PROJECT_PRODUCTION_URL
You shouldn't need to define a remote endpoint. And should definitely not be using a prod endpoint. See: https://github.com/gator-labs/chomp/blob/7c80d01eebe9610b39ddd0f73f9e6f12b56d8861/__tests__/api/mixpanel/route.test.ts#L92

2024-11-04 19:48 UTC, marvinmarnold commented on __tests__/api/user/createUserByTelegramId/route.test.ts
> +      expect(dbUser).toBeDefined();
Would be nice to make some additional assertions about the fields that we expect in dbUser.

2024-11-04 19:48 UTC, marvinmarnold commented on __tests__/api/user/createUserByTelegramId/route.test.ts
> +export async function encodeTelegramPayload(TELEGRAM_USER_PAYLOAD: any) {
Would be nice to put this in a test utility file

2024-11-04 19:48 UTC, marvinmarnold commented on __tests__/api/user/getUserByTelegramId/route.test.ts
> +      // Arrange
Nice, good to see the test split up into the three sections, for clarity.

2024-11-04 19:48 UTC, marvinmarnold commented on __tests__/api/user/setUserSubscription/route.test.ts
> +const BASE_URL = process.env.VERCEL_PROJECT_PRODUCTION_URL
Same issue that this shouldn't be necessary.

2024-11-04 19:48 UTC, marvinmarnold commented on app/api/user/createUserByTelegramId/route.ts
> +  const randomUUID = uuidv4();
This doesn't seem right to me. With our new direction, even TG users will be signed in before they use the app. We should never need to create a random UUID. It should always be available from Dynamic.

2024-11-05 11:22 UTC, neel-ds commented on __tests__/api/user/createUserByTelegramId/route.test.ts
> +const BASE_URL = process.env.VERCEL_PROJECT_PRODUCTION_URL
Good idea!

2024-11-05 11:23 UTC, neel-ds commented on __tests__/api/user/createUserByTelegramId/route.test.ts
> +      expect(dbUser).toBeDefined();
Added telegramId assertion

2024-11-05 11:25 UTC, neel-ds commented on app/api/user/createUserByTelegramId/route.ts
> +  const randomUUID = uuidv4();
I went through the Dynamic APIs and am unsure if we can create a user based on TG credentials.

2024-11-05 16:20 UTC, marvinmarnold commented on __tests__/api/user/getUserByTelegramId/route.test.ts
> +const BASE_URL = process.env.VERCEL_PROJECT_PRODUCTION_URL
Why is this necessary?

2024-11-05 16:26 UTC, marvinmarnold commented on prisma/migrations/20241029134128_add_tg_bot_fields/migration.sql
> +ADD COLUMN     "telegramId" BIGINT;
Should be distinct

2024-11-05 16:30 UTC, marvinmarnold commented on app/api/user/createUserByTelegramId/route.ts
> +  const randomUUID = uuidv4();
@neel-ds will update auto login code to always update randomly generated user ID with a Dynamic ID.

2024-11-05 19:35 UTC, marvinmarnold requested changes

2024-11-05 19:35 UTC, marvinmarnold commented on app/actions/jwt.ts
> +          profileSrc: getRandomAvatarPath(),
This will result in us updating the profile image all the time.

2024-11-05 19:35 UTC, marvinmarnold commented on app/actions/jwt.ts
> +  if (telegramUsername) {
I'm not sure this will keep working if a user changes their username

2024-11-06 13:58 UTC, neel-ds commented on app/actions/jwt.ts
> +          profileSrc: getRandomAvatarPath(),
This is the existing implementation which I added in else statement. I think `upsert` didn't change the profile before as far as I know

2024-11-06 16:20 UTC, neel-ds commented
I updated the logic for storing users based on Telegram ID instead of Telegram username.

2024-11-06 19:00 UTC, marvinmarnold requested changes

2024-11-06 19:00 UTC, marvinmarnold commented on app/actions/jwt.ts
> +        telegramUsername: telegramUsername,
This will always be null here. Might as well remove, for clarity that nothing is being set.

2024-11-07 20:43 UTC, marvinmarnold commented on app/actions/jwt.ts
> +        // If the user's Dynamic ID matches the JWT payload, then update their Telegram username incase user may have changed it
Why is it even necessary to update here? I would think that's only necessary if the username has changed.

2024-11-08 18:02 UTC, neel-ds commented
I optimized the conditional statements to handle the user data store (create or update). No additional calls will be made in any conditions if not necessary.

2024-11-08 21:03 UTC, marvinmarnold reviewed
A ew more small questions.

2024-11-08 21:03 UTC, marvinmarnold commented on app/actions/jwt.ts
> +      existingTelegramUser.id !== payload.sub ||
In what case would the tgId change? I don't think tgId should ever change.

2024-11-09 15:41 UTC, neel-ds commented on app/api/user/setUserSubscription/route.ts
> +    const user = await prisma.user.findFirst({
Good catch

2024-11-09 15:42 UTC, neel-ds commented on app/api/user/setUserSubscription/route.ts
> +        telegramUsername: telegramUserData.username,
Done

2024-11-09 15:43 UTC, neel-ds commented on app/actions/jwt.ts
> +      existingTelegramUser.id !== payload.sub ||
Telegram Id will always be the same.

2024-11-11 05:43 UTC, yash431garg commented on app/actions/jwt.ts
> +    const existingTelegramUser = await prisma.user.findFirst({
I think you can use upsert here as well and don't need to use separately insert and update.

2024-11-11 05:47 UTC, yash431garg commented on app/actions/jwt.ts
> +    return prisma.user.findUnique({
Is this necessary?

2024-11-11 05:52 UTC, yash431garg reviewed
Can you check these comments? I think it will be fine after that only getUserByTelegram test will need some updates.

2024-11-11 11:00 UTC, yash431garg approved these changes

2024-11-11 16:14 UTC, marvinmarnold approved these changes

2024-11-12 15:28 UTC, merged