PROD-419/share-reveal-single
gator-labs/chomp pull request #635
Opened 2024-10-31 14:58 UTC by danijel-radomiljac

2024-11-01 19:15 UTC, marvinmarnold requested changes
I'll look at this in more detail after the claim all share flow gets over the line so we can make sure they follow the same patterns.

2024-11-01 19:15 UTC, marvinmarnold commented on app/api/og/share-claim-all/route.tsx
> +      width: 1200,
Should be same size as designs.

2024-11-01 19:15 UTC, marvinmarnold commented on app/a/[txHash]/page.tsx
> +    `/application?${referer === "x" ? "utm_source=x&utm_medium=social&" : ""}utm_campaign=app_share&utm_content=claim_all`,
Pleas see issue description for details about constructing the UTM params.

2024-11-01 19:15 UTC, marvinmarnold commented on app/api/og/share-claim-all/route.tsx
> +  const txHash = decryptString(encryptedHash);
We still need to solve the long URL issue

2024-11-21 23:25 UTC, marvinmarnold requested changes
Left feedback: https://linear.app/gator/issue/PROD-419/share-reveal-single#comment-144f3880

2024-11-25 20:08 UTC, marvinmarnold commented
@danijel-radomiljac merge conflicts

2024-11-27 10:47 UTC, danijel-radomiljac commented
> @danijel-radomiljac og image is not loading via link [opengraph.xyz/url/https%3A%2F%2Fchomp-qrh4u8kpn-gator-labs.vercel.app%2Fs%2F5zmDqmV4nz](https://www.opengraph.xyz/url/https%3A%2F%2Fchomp-qrh4u8kpn-gator-labs.vercel.app%2Fs%2F5zmDqmV4nz)

hmm can you try again, works fine for me: https://socialsharepreview.com/?url=https://chomp-git-prod-419-share-reveal-single-gator-labs.vercel.app/s/4xof7a3KQE&1541

2024-11-28 00:00 UTC, marvinmarnold commented
This still isn't working for me.

> hmm can you try again, works fine for me: https://socialsharepreview.com/?url=https://chomp-git-prod-419-share-reveal-single-gator-labs.vercel.app/s/4xof7a3KQE&1541

Image not loading when I visit your socialsharepreview link
![Screenshot 2024-11-27 at 5 58 24 PM](https://github.com/user-attachments/assets/833e113b-3f45-4526-842b-15e76d8fb860)

Also, I notice that the image doesn't load in Twitter when I follow the embed link. But it does work when I copy the URL and post on Twitter manually. Could this be because it looks like the manual copy link has something extra at the end? `https://chomp-git-prod-419-share-reveal-single-gator-labs.vercel.app/s/2YYdspnLkk&1552`, extra = `&1552`.
![Screenshot 2024-11-27 at 5 59 02 PM](https://github.com/user-attachments/assets/0471b2c6-f1b2-497d-96b9-ed2cfb5ea72d)

2024-11-29 17:26 UTC, marvinmarnold approved these changes

2024-12-02 02:43 UTC, Yihwan commented
overall the flow looks good – it seems the image gets cut off though, wasn't sure if that's expected. 
<img width="595" alt="Screenshot 2024-12-02 at 09 43 02" src="https://github.com/user-attachments/assets/59664853-fd5b-46e2-8b47-0e64ed4f4c67">

2024-12-02 13:32 UTC, merged