PROD-402: add db constraint on fungibleAssetTransactionLog.
gator-labs/chomp pull request #649
Opened 2024-11-08 09:44 UTC by yash431garg

- Description
Previously it was possible to invoke the answer question endpoint and get as many point as user want to prevent that now we have db constraint to prevent duplicate entry for the same userId and questionId and for deckId and questionId
- What are the steps to test that this code is working?
No duplicates answer point for the same deck or question id.
- Screen shots or recordings for UI changes
N/A

2024-11-08 09:54 UTC, danijel-radomiljac approved these changes

2024-11-08 21:09 UTC, marvinmarnold requested changes

2024-11-08 21:09 UTC, marvinmarnold commented on prisma/migrations/20241030104838_add_telegram_username/migration.sql
> +ALTER TABLE "User" ADD COLUMN "telegramUsername" TEXT UNIQUE;
This looks like it was accidentally included.

2024-11-08 21:09 UTC, marvinmarnold commented on prisma/migrations/20241108065629_add_unique_deckid_userid/migration.sql
> +CREATE UNIQUE INDEX "FungibleAssetTransactionLog_deckId_userId_key" ON "FungibleAssetTransactionLog"("deckId", "userId");
Can you load the prod db to your local machine and confirm that this migration doesn't fail?

2024-11-11 06:21 UTC, yash431garg commented on prisma/migrations/20241030104838_add_telegram_username/migration.sql
> +ALTER TABLE "User" ADD COLUMN "telegramUsername" TEXT UNIQUE;
I thought there is some extra space that's why I removed that.

2024-11-11 09:29 UTC, yash431garg commented on prisma/migrations/20241108065629_add_unique_deckid_userid/migration.sql
> +CREATE UNIQUE INDEX "FungibleAssetTransactionLog_deckId_userId_key" ON "FungibleAssetTransactionLog"("deckId", "userId");
It failed and I investigated little more and find that someone has done the exploit.

2024-11-11 19:03 UTC, marvinmarnold commented on prisma/migrations/20241030104838_add_telegram_username/migration.sql
> +ALTER TABLE "User" ADD COLUMN "telegramUsername" TEXT UNIQUE;
Ah i see OK. It's fine.

2024-11-11 19:31 UTC, marvinmarnold commented on prisma/migrations/20241108065629_add_unique_deckid_userid/migration.sql
> +CREATE UNIQUE INDEX "FungibleAssetTransactionLog_deckId_userId_key" ON "FungibleAssetTransactionLog"("deckId", "userId");
As next steps, I'm asking the original reporter to confirm his wallet address. In the meantime, @yash431garg will look into a script for fixing these duplicates so that we can remove them and add the constraint.

2024-11-15 13:15 UTC, samott commented on prisma/migrations/20241108065629_add_unique_deckid_userid/migration.sql
> +CREATE UNIQUE INDEX "FungibleAssetTransactionLog_deckId_userId_key"
shouldn't this be `FungibleAssetTransactionLog_type_deckId_userId_key`?

2024-11-15 13:24 UTC, yash431garg commented on prisma/migrations/20241108065629_add_unique_deckid_userid/migration.sql
> +CREATE UNIQUE INDEX "FungibleAssetTransactionLog_deckId_userId_key"
Yes, thanks for pointing out. I have updated.

2024-11-15 13:38 UTC, samott approved these changes

2024-11-18 17:15 UTC, marvinmarnold approved these changes

2024-11-18 17:16 UTC, merged