Prod 476/mystery box without token transfer
gator-labs/chomp pull request #674
Opened 2024-11-19 12:22 UTC by yash431garg

- Description
This PR will add the breadboard for mystery box spike for staging/preview branches which can be activated with feature flag. 
- What are the steps to test that this code is working?
Get a mystery box on claim all successful.

2024-11-19 12:28 UTC, yash431garg commented
@samott I have closed the previous pr because the name wasn't correct and I have also added the schema update in this PR.

2024-11-19 17:42 UTC, marvinmarnold requested changes
Add MysteryBoxTrigger per description in ticket

2024-11-19 17:42 UTC, marvinmarnold commented on app/actions/box.ts
> +        size: BoxSize.Medium,
This value is returned by calculateMysteryBoxReward

2024-11-19 17:42 UTC, marvinmarnold commented on app/actions/box.ts
> +        size: BoxSize.Medium,
Use lower case enum values

2024-11-19 17:42 UTC, marvinmarnold commented on app/actions/box.ts
> +        prizeType: BoxPrizeType.Token,
Consider adding tokenAddress now

2024-11-21 02:57 UTC, yash431garg commented
@marvinmarnold @samott This PR is ready for your review. Please let me know if there are any further changes needed.

2024-11-21 15:42 UTC, marvinmarnold commented on app/actions/box.ts
> +"use server";
Can you add tests for both box.ts and claim.ts?

2024-11-21 15:50 UTC, marvinmarnold commented on app/actions/box.ts
> +    const tokenAddress = "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263";
Use: process.env.NEXT_PUBLIC_BONK_ADDRESS

2024-11-21 15:53 UTC, marvinmarnold commented on prisma/schema.prisma
> +enum MysteryBoxStatus {
I typically use the convention of naming enums with `E` at the beginning, like `EMysteryBoxStatus`. What do you think @samott?

2024-11-21 15:58 UTC, samott commented on prisma/schema.prisma
> +enum MysteryBoxStatus {
Make sense, but the other enums in the codebase don't follow that convention.

2024-11-21 16:05 UTC, marvinmarnold commented on prisma/schema.prisma
> +  triggerType     BoxTriggerType
This should exist on MysteryBoxTrigger instead of MysteryBox. We want to be able to support multiple trigger types for one box. We also want the same question to be a trigger for multiple trigger types.

2024-11-21 16:13 UTC, marvinmarnold commented on prisma/schema.prisma
> +  questions       MysteryBoxTrigger[]
Should be `triggers`

2024-11-21 16:16 UTC, marvinmarnold commented on prisma/schema.prisma
> +  deck            Deck?               @relation(fields: [deckId], references: [id])
This shouldn't be here. Should exist on MysteryBoxTrigger. Although not necessary yet, we will have deck triggers in the future.

2024-11-21 16:17 UTC, marvinmarnold commented on prisma/schema.prisma
> +  deckId          Int?                @unique
Remove

2024-11-21 16:17 UTC, marvinmarnold commented on prisma/schema.prisma
> +  MysteryBoxPrize MysteryBoxPrize?
Should be a one to many relationship.

2024-11-21 16:18 UTC, marvinmarnold commented on prisma/schema.prisma
> +  Question        Question[]
Remove

2024-11-21 16:21 UTC, marvinmarnold commented on prisma/schema.prisma
> +model MysteryBoxTrigger {
Type should be moved here, instead of MysteryBox

2024-11-21 16:22 UTC, marvinmarnold commented on prisma/schema.prisma
> +  mysteryBoxId String?
Add createdAt, updatedAt

2024-11-21 16:28 UTC, marvinmarnold commented on prisma/schema.prisma
> +  size              BoxSize
PrizeSize instead of BoxSize

2024-11-21 16:29 UTC, marvinmarnold commented on prisma/schema.prisma
> +  claimHash         String?
Missing claimedAt

2024-11-21 16:30 UTC, marvinmarnold commented on prisma/schema.prisma
> +  claimFungibleTxId String?
Should be Int type

2024-11-21 16:32 UTC, marvinmarnold commented on prisma/schema.prisma
> +enum BoxSize {
PrizeSize

2024-11-21 16:32 UTC, marvinmarnold commented on prisma/schema.prisma
> +enum BoxSize {
Also why lowercase values here but other enums are capitalized?

2024-11-21 16:33 UTC, marvinmarnold commented on prisma/schema.prisma
> +  MysteryBox                  MysteryBox?                   @relation(fields: [mysteryBoxId], references: [id])
Relationship should be with MysteryBoxPrize, not MysteryBox

2024-11-21 16:33 UTC, marvinmarnold commented on prisma/schema.prisma
> +  MysteryBox                  MysteryBox?
Not sure why this is here

2024-11-21 16:40 UTC, marvinmarnold commented on app/utils/algo.ts
> +    event_type: "share",
"share" should be referenced from an enum

2024-11-21 17:00 UTC, marvinmarnold commented on prisma/schema.prisma
> +enum BoxSize {
Small
Medium
Large

we'll change in mechanism engine

2024-11-21 17:07 UTC, marvinmarnold commented on app/actions/box.ts
> +    console.log(e);
I think if you do console.error, that will cause Sentry to track this. We do want Sentry to track.

Also, user should see an error in this case.

2024-11-22 10:16 UTC, yash431garg commented on prisma/schema.prisma
> +enum MysteryBoxStatus {
Let's start the convention from this PR.

2024-11-22 10:25 UTC, yash431garg commented on prisma/schema.prisma
> +enum BoxSize {
@samott we need to change in mechanism engine as well.

2024-11-22 14:12 UTC, samott commented on prisma/schema.prisma
> +enum BoxSize {
@yash431garg I already made the change

2024-11-22 21:57 UTC, marvinmarnold commented
@yash431garg is this ready for review again?

2024-11-23 18:36 UTC, samott commented on app/components/ClaimShareDrawer/ClaimShareDrawer.tsx
> +  const [showMysterBox, setShowMysterBox] = useState(false);
Typo in the name above.

2024-11-24 09:51 UTC, neel-ds commented on app/components/ClaimShareDrawer/ClaimShareDrawer.tsx
> +  const [showMysterBox, setShowMysterBox] = useState(false);
Good catch, I renamed it.

2024-11-25 09:08 UTC, yash431garg commented on prisma/schema.prisma
> +enum BoxSize {
Thanks,

2024-11-25 17:22 UTC, merged

2024-11-26 00:51 UTC, marvinmarnold commented on app/actions/claim.ts
> +  mysteryBoxId?: string | null,
I don't get why claimQuestions would need to depend on a mysteryBoxId

2024-11-26 00:55 UTC, marvinmarnold commented on app/actions/mysteryBox.ts
> +      Number(reward?.MysteryBoxPrize[0]?.amount),
Shouldn't assume that BONK will always be the first prize returned by mechanism engine.

2024-11-26 00:56 UTC, marvinmarnold commented on app/actions/mysteryBox.ts
> +    revalidatePath("/application/history");
Doesn't revalidate(/application) revalidate child paths like /history too?

2024-11-26 00:57 UTC, marvinmarnold commented on app/actions/mysteryBox.ts
> +    await prisma.mysteryBoxPrize.update({
Combine this with update below

2024-11-26 00:59 UTC, marvinmarnold commented on app/actions/mysteryBox.ts
> +export async function handleSendBonk(rewardAmount: number, address: string) {
Refactor duplicative code.

2024-11-26 01:02 UTC, marvinmarnold commented on app/components/MysteryBox/MysteryBox.tsx
> +            <p className="text-base text-secondary font-bold">Myster Box</p>
Missing y

2024-11-26 01:04 UTC, marvinmarnold commented on app/utils/algo.ts
> +    event_type: MysteryBoxEventsType.SHARE,
Should be ClaimAllCompleted. But should also be a parameter and not a hard coded event_type.

2024-11-26 01:06 UTC, marvinmarnold commented on prisma/schema.prisma
> +  ClaimAll
ClaimAllCompleted

2024-11-26 02:21 UTC, yash431garg commented on app/actions/claim.ts
> +  mysteryBoxId?: string | null,
We will get the mystery box Id here and it will complete the rest of the flow. https://github.com/gator-labs/chomp/blob/fbb6f1c0bdb0cbf4861d782131c9102d66cfc39f/app/components/History/TotalRewardsClaimAll/TotalRewardsClaimAll.tsx#L74

2024-11-26 02:25 UTC, yash431garg commented on app/actions/mysteryBox.ts
> +      Number(reward?.MysteryBoxPrize[0]?.amount),
Make sense @neel-ds can you validate it with the tokenAddress field that whether this is related to BONK reward.

2024-11-26 06:34 UTC, yash431garg commented on app/utils/algo.ts
> +    event_type: MysteryBoxEventsType.SHARE,
Sure,