PROD-499/fix-claim-when-revealed-with-nft
gator-labs/chomp pull request #675
Opened 2024-11-19 13:04 UTC by danijel-radomiljac

2024-11-19 20:24 UTC, marvinmarnold requested changes
Left notes on Linear with issues

2024-11-21 21:43 UTC, marvinmarnold submitted a review, later dismissed

2024-11-21 21:44 UTC, marvinmarnold commented
@samott please review

2024-11-21 22:13 UTC, samott commented on app/api/og/share-claim-all/route.tsx
>        },
We could maybe do with a DB index on these fields

2024-11-25 09:16 UTC, samott approved these changes

2024-11-25 09:17 UTC, merged