feat: Add connect telegram and x functionality with hi-fi design
gator-labs/chomp pull request #685
Opened 2024-11-21 11:45 UTC by yash431garg

- Description
User will be able to link/unlink x and telegram account from their connected wallet address simultaneously updating the database. 
- Screen shots or recordings for UI changes
<img width="498" alt="Screenshot 2024-11-21 at 5 07 49 PM" src="https://github.com/user-attachments/assets/2760c05b-003c-44ee-b860-98f73e6d6c80">

2024-11-21 22:27 UTC, marvinmarnold requested changes
![Screenshot 2024-11-21 at 4 26 51 PM](https://github.com/user-attachments/assets/adcf5164-1ffd-437a-b0a6-e1ee29c14621)

I'm not able to load the login screen for some reason.

2024-11-21 22:27 UTC, marvinmarnold commented on app/actions/user.ts
> +"use server";
Can you rename the file to addUserSocials?

2024-11-21 22:27 UTC, marvinmarnold commented on app/components/SocialAuth/SocialAuth.tsx
> +      {userTelegramInfo ? (
Doesn't look like this follows the AC "It should not be possible to disconnect TG if user signed up through the bot and there is no other wallet associated with the account."

2024-11-22 05:34 UTC, yash431garg commented on app/components/SocialAuth/SocialAuth.tsx
> +      {userTelegramInfo ? (
I think I missed that.

2024-11-22 10:26 UTC, yash431garg commented
> * Description
>   User will be able to link/unlink x and telegram account from their connected wallet address simultaneously updating the database.
> * Screen shots or recordings for UI changes
> 
> <img alt="Screenshot 2024-11-21 at 5 07 49 PM" width="498" src="https://private-user-images.githubusercontent.com/74279656/388490262-2760c05b-003c-44ee-b860-98f73e6d6c80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNzE0NjIsIm5iZiI6MTczMjI3MTE2MiwicGF0aCI6Ii83NDI3OTY1Ni8zODg0OTAyNjItMjc2MGMwNWItMDAzYy00NGVlLWI4NjAtOThmNzNlNmQ2YzgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDEwMjYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3OWY5MTA0NjczNzNlOTZiY2U3YjUzYTBjMzRhZDljYWQzMDU5YmM1ZDE1ODdjNTI4ZGRmNzkyYzU0ZDM0MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cvOzTH1126Zh4n3x4dos7PwujllkoQ0ANJPTYq_41mM">

Done it was because of missing db migration. Now it should be working.

2024-11-22 10:27 UTC, yash431garg commented
> Done it was because of missing db migration. Now it should be working.

Done it was because of missing db migration. Now it should be working.

2024-11-22 10:27 UTC, yash431garg commented
> ![Screenshot 2024-11-21 at 4 26 51 PM](https://private-user-images.githubusercontent.com/1311030/388719602-adcf5164-1ffd-437a-b0a6-e1ee29c14621.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNzE0NjIsIm5iZiI6MTczMjI3MTE2MiwicGF0aCI6Ii8xMzExMDMwLzM4ODcxOTYwMi1hZGNmNTE2NC0xZmZkLTQzN2EtYjBhNi1lMWVlMjljMTQ2MjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjJUMTAyNjAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWQ1ZjcxYTQ2MjQ1ZTU2M2Q3N2ZlMTFiZWQ1YjlhNWFiYjNhOWVkYTE4ZTI5ZTc1Nzc3ZjI2ODUzZWU0YTFhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.CP_kofK1nY3IrSE7ybOoWJ-3qXX-W_lIdkNzA9o7S_0)
> 
> I'm not able to load the login screen for some reason.

Done it was because of missing db migration. Now it should be working.

2024-11-22 22:11 UTC, marvinmarnold commented
> Resolved it was because of missing db migration. Now it should be working.

Oh ok. This points out that we don't have a very clear process for how to handle migrations in staging. Some thoughts/questions

1. To fix the issue, did you manually run the migrations on staging? In some cases, that will cause the GH workflow to fail because it will try to reapply a duplicate change like "create index". It also gives us less confidence that the subsequent release to prod will work as expected.
2. An alternative approach is to first review the code, then merge into staging and test again there after migrations run. In this case, devs should just note that preview link wont work. 
3. We could also consider implementing some better dev infra. For example DB branching so there's a separate DB per preview link.

I think #2 is fine for now. It's pretty risk free to test things in staging.

 cc @samott

2024-11-23 05:27 UTC, yash431garg commented
> > Resolved it was because of missing db migration. Now it should be working.
> 
> Oh ok. This points out that we don't have a very clear process for how to handle migrations in staging. Some thoughts/questions
> 
> 1. To fix the issue, did you manually run the migrations on staging? In some cases, that will cause the GH workflow to fail because it will try to reapply a duplicate change like "create index". It also gives us less confidence that the subsequent release to prod will work as expected.
> 2. An alternative approach is to first review the code, then merge into staging and test again there after migrations run. In this case, devs should just note that preview link wont work.
> 3. We could also consider implementing some better dev infra. For example DB branching so there's a separate DB per preview link.
> 
> I think #2 is fine for now. It's pretty risk free to test things in staging.
> 
> cc @samott

Yes, I manually run the migrations. If we go with #2 Will we be testing the features in staging link and not in the preview branch.

2024-11-23 17:36 UTC, marvinmarnold commented
Old comment:

@yash431garg I'm still getting these errors

- Twitter error
![Screenshot 2024-11-22 at 9 24 10 PM](https://github.com/user-attachments/assets/f3be0031-1790-41a7-bddb-ea503b3b0835)
- TG not working
![Screenshot 2024-11-22 at 9 25 15 PM](https://github.com/user-attachments/assets/9db18a7a-92b6-4f25-b351-ba28cc7cc558)

2024-11-23 17:52 UTC, marvinmarnold requested changes
@yash431garg this looks like it's working. but some follow ups:
- Can you add details in README or Notion about how to get X and Telegram keys necessary for setup? also about how to configure Dynamic correctly.
- Depending on the steps above, we may need to put one or both account linking options behind and env var feature flag.
- I'll have to test that tg can't be unlinked when sign up happens through bot after you merge into staging. 

> Yes, I manually run the migrations. If we go with https://github.com/gator-labs/chomp/pull/2 Will we be testing the features in staging link and not in the preview branch.

Yup. That's not ideal, but I think it's a good enough process for now.

2024-11-24 13:15 UTC, yash431garg commented
> @yash431garg this looks like it's working. but some follow ups:
> 
> * Can you add details in README or Notion about how to get X and Telegram keys necessary for setup? also about how to configure Dynamic correctly.
> * Depending on the steps above, we may need to put one or both account linking options behind and env var feature flag.
> * I'll have to test that tg can't be unlinked when sign up happens through bot after you merge into staging.
> 
> > Yes, I manually run the migrations. If we go with #2 Will we be testing the features in staging link and not in the preview branch.
> 
> Yup. That's not ideal, but I think it's a good enough process for now.

I have tested unlink telegram but dynamic throws an error and I have also added a custom error but let me know if you get any error.

2024-11-24 16:52 UTC, marvinmarnold approved these changes
I tested it and it works well. I also created a follow up task for us to discuss: https://linear.app/gator/issue/PROD-504/improve-infra-for-demo-environment

2024-11-24 17:00 UTC, marvinmarnold commented
Can you also test that tx signing works if you:

1. sign up with Phantom
2. connect Telegram
3. sign out
4. sign in with Telegram
5. try to reveal

It should still let you use Phantom burn. @neel-ds is this the edge case you were talking about, or did I misunderstand?

2024-11-24 18:37 UTC, yash431garg commented
> Can you also test that tx signing works if you:
> 
> 1. sign up with Phantom
> 2. connect Telegram
> 3. sign out
> 4. sign in with Telegram
> 5. try to reveal
> 
> It should still let you use Phantom burn. @neel-ds is this the edge case you were talking about, or did I misunderstand?

I have tested that you can check the comments on linear.

2024-11-25 05:06 UTC, yash431garg commented
> > Can you also test that tx signing works if you:
> > 
> > 1. sign up with Phantom
> > 2. connect Telegram
> > 3. sign out
> > 4. sign in with Telegram
> > 5. try to reveal
> > 
> > It should still let you use Phantom burn. @neel-ds is this the edge case you were talking about, or did I misunderstand?
> 
> I have tested that and you can check the comments on linear. https://linear.app/gator/issue/PROD-457/link-telegram-andor-x-account-from-profile#comment-5043b1db

2024-11-25 11:04 UTC, Yihwan approved these changes

2024-11-25 16:23 UTC, merged