PROD-460 added question answer status check
gator-labs/chomp pull request #689
Opened 2024-11-23 17:24 UTC by AndrejRadomiljac

✅ Add Linear ID (e.g., `PROD-123`) to PR title to automatically link issue

- Description
- Link to the task -> https://linear.app/gator/issue/PROD-460/prevent-updating-question-once-answered. 
  After answering the question user should not be able to answer to the same question again. Right now, there is a check if someone triggers answer action and that question has already answered (status === 'submited') then we throw an error.
- What are the steps to test that this code is working?
  Go to some deck in order to answer the question. Before answering open the network tab. Pay attention after submitting to the network tab and select the answer action. Copy the cUrl as it is provided in the screenshot:
<img width="1728" alt="Screenshot 2024-11-23 at 18 18 49" src="https://github.com/user-attachments/assets/1e18f2f6-07e9-4505-8910-f1adf01b6683">
Paste that in your terminal and as a result there should be an error that says that user has already answered the question.
<img width="1728" alt="Screenshot 2024-11-23 at 18 18 38" src="https://github.com/user-attachments/assets/837b5bce-250c-4d16-81dd-0101b09e1b53">

- Screen shots or recordings for UI changes

2024-11-23 17:56 UTC, marvinmarnold requested changes
Can you add a test case that `answerQuestion` won't create an answer twice? [Example](https://github.com/gator-labs/chomp/blob/main/__tests__/actions/deck/deck-editDeck.test.ts). 

Is there also some DB constraint that we can add so that QuestionAnswers are unique by (questionOptionId, userId)?

2024-11-23 18:25 UTC, samott commented on app/actions/answer.ts
> +
Do you think it would be more efficient to integrate the check into the database query?

I also wonder if the guard should be inside the transaction below to avoid a race condition.

2024-11-23 19:06 UTC, AndrejRadomiljac commented
> Can you add a test case that `answerQuestion` won't create an answer twice? [Example](https://github.com/gator-labs/chomp/blob/main/__tests__/actions/deck/deck-editDeck.test.ts).
> 
> Is there also some DB constraint that we can add so that QuestionAnswers are unique by (questionOptionId, userId)?

Yes, I can add test case to confirm this. Unique constraint already exists.

2024-11-23 19:54 UTC, marvinmarnold commented
Thanks for that clarification. For me the most important piece is that `answerQuestion` is tested. And that we're sure there aren't any other code paths by which a user can answer. I defer to you all who are in the code more about when we should refactor.

2024-11-24 04:41 UTC, marvinmarnold approved these changes

2024-11-24 09:42 UTC, samott approved these changes

2024-11-25 19:11 UTC, merged