PROD-512 added error state for answering revealed questions
gator-labs/chomp pull request #704
Opened 2024-11-28 18:38 UTC by AndrejRadomiljac

✅ Add Linear ID (e.g., `PROD-123`) to PR title to automatically link issue
Link to the Linear https://linear.app/gator/issue/PROD-512/ensure-its-not-possible-to-answer-questions-that-have-already-been
- Description
- User was able to answer the revealed question. I've added condition that excludes those questions and throws error in that case. I've also added tests, but after latest updates on staging I am not able to run any test. I am creating PR without tests until we figure out what is causing the issue.
- What are the steps to test that this code is working?
- Screen shots or recordings for UI changes

2024-11-29 17:36 UTC, marvinmarnold requested changes

2024-11-29 17:36 UTC, marvinmarnold commented on __tests__/actions/answer/answer-revealed-question.test.ts
> +    expect(deleteManyMock).toHaveBeenCalledWith({
Generally, I think `toHaveBeenCalled` should be avoided. Tests should be oriented around testing real user flows. In this case, I would not mock the DB connection. You can then make assertions about the entry in the DB.

This won't be a true user test. But it will give us more confidence that the underlying behavior works and won't be implementation specific.

2024-11-29 17:36 UTC, marvinmarnold commented on __tests__/actions/answer/answer-revealed-question.test.ts
> +    expect(prisma.questionAnswer.createMany).not.toHaveBeenCalled();
Similar to my other comment. I would assert that DB does not have any new entries. Instead of asserting that createMany wasn't called.

2024-11-29 17:44 UTC, AndrejRadomiljac commented on __tests__/actions/answer/answer-revealed-question.test.ts
> +    expect(deleteManyMock).toHaveBeenCalledWith({
expect(deleteManyMock).toHaveBeenCalledWith
expect(deleteManyMock).toHaveBeenCalledWith
are leftovers. My bad. But generally, generally this test is E2E test where I send data to the API endpoint and check the response. In this case we expect error, due the revealAt date. That's the reason why I intentionally inserted DB records. There is no other way to test, because you need to be aware of question ids that should be part of test. Unit test for this does not make sense since you we are trying to test the ORM gte method. @marvinmarnold

2024-11-29 17:47 UTC, AndrejRadomiljac commented
I've mixed somehow test for answer revealed and answer twice. Now everything is up to date.

2024-11-29 17:49 UTC, marvinmarnold submitted a review, later dismissed

2024-11-29 17:49 UTC, marvinmarnold commented on __tests__/actions/answer/answer--revealed-question.test.ts
> +      expect(error.message).toBe(
> are leftovers. My bad. But generally, generally this test is E2E test

Gotcha. I think this test could still be stronger if you asserted that the only answers that exist in the DB are the ones created in setup. Otherwise it's possible that the API is just returning an exception, but actually a new answer was actually inserted.

2024-11-29 17:54 UTC, marvinmarnold commented on __tests__/actions/answer/answer--revealed-question.test.ts
> +import { SaveQuestionRequest, answerQuestion } from "@/app/actions/answer";
This filename also has an extra `-`

2024-12-04 13:58 UTC, marvinmarnold commented
@AndrejRadomiljac are you going to do follow up on this or are you waiting for reviews?

2024-12-05 16:24 UTC, danijel-radomiljac submitted a review, later dismissed

2024-12-05 16:34 UTC, merged