PROD-523: Add Mysterybox Allowlist
gator-labs/chomp pull request #719
Opened 2024-12-06 17:01 UTC by neel-ds

- Description

It replaces the Mystery Box FF with Allowlist. It contains schema update to support batch of different campaigns. 

- What are the steps to test that this code is working?
Use the script to add your address in allowlist and claim the rewards. You will see the mystery box.

- Screen shots or recordings for UI changes
NA

2024-12-06 17:08 UTC, samott commented on app/actions/claim.ts
> +export async function isUserInAllowlist(): Promise<boolean> {
Actions should get their own file, but this is a utility so should go in `lib` or `utils` (outside `app`)

2024-12-06 17:09 UTC, samott commented on app/actions/mysteryBox/reward.ts
> +              mysteryBoxAllowlistId: user?.wallets[0].address ?? "",
As above, we probably want to check all wallets.

2024-12-06 17:10 UTC, samott commented on app/components/ClaimShareDrawer/ClaimShareDrawer.tsx
> +  }, []);
Seems like we only need to check this if `mysteryBoxId` is defined.

2024-12-06 17:13 UTC, samott commented on app/components/ClaimShareDrawer/ClaimShareDrawer.tsx
> +  }, []);
In fact, `mysteryBoxId` won't ever be defined if the user isn't whitelisted, right? Maybe we don't need this check.

2024-12-08 10:46 UTC, neel-ds commented on app/actions/mysteryBox/reward.ts
> +              mysteryBoxAllowlistId: user?.wallets[0].address ?? "",
Here, it adds current user wallet while creating mystery box & mystery box trigger.

2024-12-09 13:28 UTC, samott approved these changes

2024-12-09 20:34 UTC, marvinmarnold requested changes

2024-12-09 20:34 UTC, marvinmarnold commented on scripts/addAllowlistUsers.ts
> +    skipDuplicates: true,
This means that an address will only ever have one tag, since we don't append new ones. Not a blocker because it's a small detail. We'll also always have the original CSVs as reference.

2024-12-09 20:34 UTC, marvinmarnold commented on yarn.lock
Remove this file from PR and merge in changes from main.

2024-12-09 20:34 UTC, marvinmarnold commented on app/actions/claim.ts
> +  const isAllowlisted = await isUserInAllowlist();
Allow list only relevant for CHOMPmas mystery box. ClaimAllCompleted does not require presence in allowlist.

2024-12-09 20:34 UTC, marvinmarnold commented on app/components/ClaimShareDrawer/ClaimShareDrawer.tsx
> +      {showMysteryBox && mysteryBoxId ? (
FF_MYSTERY_BOX should still be used.

2024-12-09 20:34 UTC, marvinmarnold commented on lib/mysteryBox.ts
> +    console.log("Error in isUserInAllowlist", e);
Should console.error so that it's automatically sent to Sentry

2024-12-09 20:34 UTC, marvinmarnold commented on README.md
> +
Thank you for adding docs!

2024-12-10 09:53 UTC, neel-ds commented on scripts/addAllowlistUsers.ts
> +    skipDuplicates: true,
Yes, Do you want me to change the datatype -> String[]?

2024-12-10 09:56 UTC, neel-ds commented on app/actions/claim.ts
> +  const isAllowlisted = await isUserInAllowlist();
This condition is used to create mysteryBox once ClaimAllCompleted. If user doesn't exist in allowlist then it won't even create mysteryBox.

2024-12-10 15:58 UTC, marvinmarnold commented
@samott will merge your work into his and open a new pr

2024-12-10 15:58 UTC, closed without merging