Prod 532/rpc tx confirmation backend
gator-labs/chomp pull request #720
Opened 2024-12-08 12:54 UTC by yash431garg

- Description
1. Reveal refactoring
2. Remove tx confirmation from frontend
3. Update burntx creation
4. Send sentry error if tx not validated.

2024-12-09 17:03 UTC, marvinmarnold commented on app/utils/solana.ts
>    tx.add(modifyComputeUnits);
const burnTx = new Transaction();
burnTx.add(modifyComputeUnits);
burnTx.add(addPriorityFee);
burnTx.add(burnTxInstruction);

2024-12-09 17:14 UTC, marvinmarnold commented on app/hooks/useReveal.ts
> +          //   await deleteQuestionChompResults(pendingChompResultIds);
Do all this
1. can be deleted
2. copied and moved to backend function
3. Check for expired blockhash specifically and delete ChompResults in that case only. Otherwise create ChompResult in state `ValidationFailed`.

2024-12-09 17:22 UTC, marvinmarnold commented on app/actions/chompResult.ts
> +// tx validation with 5 retries with a delay of 1s
Call confirmTransaction first. It will either return:
1. Success -> Continue on to getParsedTransaction
2. Fail with expired blockhash -> Delete ChompResult. Do not continue.
3. Fail with unknown error -> Continue on to getParsedTransaction

Call getParsedTransaction
1. Success -> Update record to Completed
2. Failure -> Update record to VerificationFailed

2024-12-10 06:09 UTC, yash431garg commented on app/actions/chompResult.ts
> +// tx validation with 5 retries with a delay of 1s
Check for expired blockhash specifically and delete ChompResults in that case only. Otherwise create ChompResult in state ValidationFailed.

2024-12-10 06:15 UTC, marvinmarnold commented on app/utils/solana.ts
>    tx.add(addPriorityFee);
Should we also move this up to before where we add the burnTx?

2024-12-10 13:06 UTC, yash431garg commented on app/actions/chompResult.ts
> +// tx validation with 5 retries with a delay of 1s
I am not marking chompResult as ValidationFailed here because in the cron job we will fetch the pending requests and if cron still not able to verify the tx than we will mark it is as Failed it will help in double verification this way.

2024-12-10 17:37 UTC, marvinmarnold requested changes
Reveal all not working: https://linear.app/gator/issue/PROD-532/reveal-move-rpc-tx-confirmation-to-backend#comment-538ab9ac

2024-12-11 14:22 UTC, marvinmarnold commented on app/actions/validateBonkBurn.ts
Move into lib. And can remove SECRET.

2024-12-11 14:24 UTC, marvinmarnold commented on app/api/process-pending-transaction/route.ts
> +  const SECRET = process.env.CRON_SECRET || "";
SECRET should be lower case

2024-12-11 14:45 UTC, marvinmarnold commented on lib/validateBonkBurn.ts
> +        "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",
Use constant for this

2024-12-14 15:32 UTC, merged