PROD-539 added UI for scripts
gator-labs/chomp pull request #733
Opened 2024-12-11 21:36 UTC by AndrejRadomiljac

✅ Add Linear ID (e.g., `PROD-123`) to PR title to automatically link issue

- Description
- Link to the task https://linear.app/gator/issue/PROD-539/create-ui-that-runs-devmc-obj-on-staging
- What are the steps to test that this code is working?
- Screen shots or recordings for UI changes
<img width="726" alt="Screenshot 2024-12-11 at 22 34 03" src="https://github.com/user-attachments/assets/0489a4a1-4e7d-431b-963d-9d573f944599" />

https://github.com/user-attachments/assets/b98b1d92-cea6-413c-858e-f04d17dec627

2024-12-11 22:20 UTC, marvinmarnold requested changes
To prevent this from running in staging can you make the default behavior that it doesn't show, but it does show if FF_ALLOW_TEST_QUESTIONS is set to true?

Add the env var to .env.example.

2024-12-12 08:41 UTC, AndrejRadomiljac commented
> To prevent this from running in staging can you make the default behavior that it doesn't show, but it does show if FF_ALLOW_TEST_QUESTIONS is set to true?
> 
> Add the env var to .env.example.

Absolutely. What should be displayed if suggested variable is false?

2024-12-12 09:21 UTC, AndrejRadomiljac commented
<img width="726" alt="Screenshot 2024-12-12 at 10 21 15" src="https://github.com/user-attachments/assets/423bcedb-a3e2-4508-bb77-b79561015bd4" />

2024-12-12 09:27 UTC, AndrejRadomiljac commented
All tests failed due to Mystery box test

2024-12-13 13:09 UTC, yash431garg commented on app/components/AdminMultiChoiceQuestionGeneratorForm/AdminMultiChoiceQuestionGeneratorForm.tsx
Can we create a reusable comment?

2024-12-13 14:27 UTC, AndrejRadomiljac commented on app/components/AdminMultiChoiceQuestionGeneratorForm/AdminMultiChoiceQuestionGeneratorForm.tsx
It can be, but since this is just for testing purpose, I do not think we should spend time on this anymore

2024-12-13 15:28 UTC, yash431garg approved these changes
LGTM

2024-12-13 18:02 UTC, merged