PROD-511/flaky-deck-tests - [WIP]
gator-labs/chomp pull request #762
Opened 2024-12-18 09:34 UTC by danijel-radomiljac

2024-12-18 13:36 UTC, marvinmarnold approved these changes

2024-12-18 13:36 UTC, marvinmarnold requested changes
I think we added `test.skip` to prevent the tests from failing. Can you remove that?

2024-12-18 13:57 UTC, danijel-radomiljac commented
> I think we added `test.skip` to prevent the tests from failing. Can you remove that?

skip only exitsts in this file rewards-mc-obj.test.ts @marvinmarnold

2024-12-18 17:43 UTC, marvinmarnold approved these changes

2024-12-19 11:40 UTC, samott approved these changes

2024-12-20 10:15 UTC, merged