feat: add credit cost to deck
gator-labs/chomp pull request #802
Opened 2024-12-26 07:41 UTC by yash431garg

- Description
Show credist balance on decks with feature flag
- What are the steps to test that this code is working?
Credit balance will be visible before the deck begin if the feature flag is true.
- Screen shots or recordings for UI changes

2024-12-27 11:13 UTC, neel-ds approved these changes

2024-12-27 12:10 UTC, neel-ds commented on app/screens/DeckScreens/DeckScreen.tsx
> +    process.env.NEXT_PUBLIC_FF_CREDIT_COST_PER_QUESTION === "true";
This could cause a case sensitivity issue. Maybe you can assign the env value directly without condition.

2024-12-30 14:07 UTC, marvinmarnold requested changes

2024-12-30 14:07 UTC, marvinmarnold commented on app/screens/DeckScreens/DeckScreen.tsx
> +                <span className="opacity-50 text-chomp-red-dark">
Should be more bold

2024-12-30 15:43 UTC, marvinmarnold approved these changes

2024-12-30 17:14 UTC, neel-ds approved these changes

2024-12-30 17:24 UTC, neel-ds approved these changes

2024-12-30 17:56 UTC, merged